// data-docs.js — les 70 fiches issues du dossier Docs/.
//
// IMPORTANT : les PDF d'origine n'ont jamais été versionnés (seuls les noms de
// fichiers l'avaient été), et ils sont aujourd'hui perdus. Ces recettes ont donc
// été RECONSTITUÉES à partir du titre de chaque fiche et de recettes de
// référence trouvées en ligne. Les quantités et les étapes sont plausibles et
// cohérentes, mais elles ne reproduisent pas les documents originaux.
//
// D'où le drapeau `reconstructed: true` : l'app l'affiche pour que ces fiches
// puissent être relues et corrigées. Une fois une recette vérifiée et corrigée
// à la main, retirer le drapeau sur cette entrée.

const r = (id, name, cat, time, portions, ingredients, steps) => ({
  id, name, cat, time, portions,
  ingredients: ingredients.map(([qty, unit, n]) => ({ qty, unit, name: n })),
  steps,
  reconstructed: true,
});

export const DOCS_RECIPES = [
  // ============================ PLATS ============================
  r('docs-plats-bouglour-lentilles-poulet', 'Bouglour et lentilles corail émincés de poulet courgette et carottes', 'volaille', 35, 4, [
    [150, 'g', 'Boulgour'], [150, 'g', 'Lentilles corail'], [500, 'g', 'Blanc de poulet'],
    [1, 'pc', 'Courgette'], [2, 'pc', 'Carotte'], [1, 'pc', 'Oignon'], [2, 'gousse', 'Ail'],
    [2, 'cc', 'Curry'], [1, 'cc', 'Curcuma'], [2, 'cs', 'Huile d\'olive'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Rincer les lentilles corail. Les cuire 10 minutes à l\'eau bouillante salée, égoutter.',
    'Cuire le boulgour selon les indications du paquet, puis l\'égrainer à la fourchette.',
    'Couper le poulet en émincés. Le saisir 5 minutes à l\'huile bien chaude, réserver.',
    'Dans la même poêle, faire revenir l\'oignon et l\'ail hachés, puis les carottes en rondelles 5 minutes.',
    'Ajouter la courgette en dés, le curry et le curcuma, poursuivre 5 minutes.',
    'Réunir boulgour, lentilles, légumes et poulet. Rectifier sel et poivre, servir chaud.',
  ]),
  r('docs-plats-cabillaud-curry', 'Cabillaud aux légumes et au curry rouge', 'poisson', 30, 4, [
    [700, 'g', 'Cabillaud'], [400, 'ml', 'Lait de coco'], [2, 'cs', 'Pâte de curry'],
    [1, 'pc', 'Courgette'], [2, 'pc', 'Carotte'], [1, 'pc', 'Poivron'],
    [1, 'pc', 'Oignon'], [2, 'gousse', 'Ail'], [200, 'g', 'Riz'],
    [1, 'cs', 'Huile d\'olive'], [1, 'pc', 'Citron vert'], [1, 'pincée', 'Sel'],
  ], [
    'Émincer l\'oignon et l\'ail, les faire revenir à l\'huile jusqu\'à ce qu\'ils soient translucides.',
    'Ajouter les carottes en demi-rondelles, la courgette en quartiers et le poivron en lanières.',
    'Incorporer la pâte de curry rouge, bien enrober les légumes.',
    'Verser le lait de coco, saler légèrement et laisser mijoter 10 minutes à feu moyen.',
    'Déposer le cabillaud en gros morceaux dans la sauce, couvrir et cuire 8 à 10 minutes.',
    'Servir sur le riz, avec des quartiers de citron vert.',
  ]),
  r('docs-plats-conchiglioni-farcis', 'Conchiglioni farcis ricotta épinards', 'four', 45, 4, [
    [300, 'g', 'Pâtes'], [400, 'g', 'Ricotta'], [400, 'g', 'Épinards'],
    [1, 'pc', 'Oeuf'], [80, 'g', 'Parmesan'], [600, 'g', 'Sauce tomate'],
    [1, 'pc', 'Oignon'], [1, 'cs', 'Huile d\'olive'],
    [1, 'pincée', 'Noix de muscade'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Faire revenir l\'oignon émincé à l\'huile, ajouter la sauce tomate et laisser réduire 15 minutes.',
    'Cuire les épinards, les égoutter en pressant bien, puis les hacher finement.',
    'Mélanger épinards, ricotta, œuf, la moitié du parmesan, la muscade, le sel et le poivre.',
    'Précuire les conchiglioni 6 minutes à l\'eau salée, les rafraîchir et les égoutter.',
    'Étaler un fond de sauce dans un plat, garnir chaque pâte de farce et les ranger dessus.',
    'Napper du reste de sauce, parsemer de parmesan et enfourner 25 minutes à 190 °C.',
  ]),
  r('docs-plats-courgette-farcie-quinoa', 'Courgette farcie au quinoa', 'vege', 45, 4, [
    [4, 'pc', 'Courgette'], [180, 'g', 'Quinoa'], [1, 'pc', 'Oignon'],
    [2, 'gousse', 'Ail'], [200, 'g', 'Tomate'], [100, 'g', 'Feta'],
    [80, 'g', 'Fromage râpé'], [2, 'cs', 'Huile d\'olive'],
    [1, 'cc', 'Origan'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Cuire le quinoa 12 minutes à l\'eau salée, égoutter.',
    'Couper les courgettes en deux dans la longueur, les évider à la cuillère et réserver la chair.',
    'Faire revenir l\'oignon, l\'ail et la chair de courgette hachés 8 minutes à l\'huile.',
    'Ajouter les tomates en dés et l\'origan, cuire 5 minutes, puis mélanger au quinoa et à la feta émiettée.',
    'Garnir les demi-courgettes, parsemer de fromage râpé.',
    'Enfourner 25 minutes à 190 °C jusqu\'à ce que le dessus soit doré.',
  ]),
  r('docs-plats-croque-saumon', 'Croque monsieur au saumon', 'rapide', 20, 4, [
    [8, 'tranche', 'Pain'], [200, 'g', 'Saumon'], [150, 'g', 'Fromage blanc'],
    [100, 'g', 'Fromage râpé'], [1, 'pc', 'Citron'], [20, 'g', 'Beurre'],
    [1, 'botte', 'Aneth'], [1, 'pincée', 'Poivre'],
  ], [
    'Mélanger le fromage blanc avec l\'aneth ciselée, un trait de jus de citron et du poivre.',
    'Tartiner quatre tranches de pain de ce mélange.',
    'Répartir le saumon fumé dessus, couvrir de fromage râpé puis refermer avec les autres tranches.',
    'Beurrer légèrement l\'extérieur des croques.',
    'Dorer 3 à 4 minutes par face à la poêle ou à l\'appareil à croque-monsieur.',
    'Couper en deux et servir aussitôt avec une salade verte.',
  ]),
  r('docs-plats-crepes-salees', 'Crêpes salées idées', 'rapide', 30, 4, [
    [250, 'g', 'Farine'], [500, 'ml', 'Lait'], [3, 'pc', 'Oeufs'],
    [200, 'g', 'Jambon'], [150, 'g', 'Champignons de Paris'], [150, 'g', 'Fromage râpé'],
    [200, 'g', 'Épinards'], [30, 'g', 'Beurre'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Fouetter la farine, les œufs, le lait et une pincée de sel. Laisser reposer la pâte 30 minutes.',
    'Cuire les crêpes à la poêle beurrée, environ 1 minute par face, et les empiler.',
    'Faire suer les champignons émincés, ajouter les épinards et laisser rendre l\'eau.',
    'Garniture 1 : jambon et fromage râpé, à refermer et faire fondre à la poêle.',
    'Garniture 2 : épinards et champignons, à rouler puis gratiner 10 minutes à 190 °C.',
    'Poivrer et servir chaud.',
  ]),
  r('docs-plats-ebly-legumes-jambon', 'Ebly légumes et jambon au four', 'four', 40, 4, [
    [250, 'g', 'Ebly'], [250, 'g', 'Jambon'], [1, 'pc', 'Courgette'],
    [2, 'pc', 'Carotte'], [1, 'pc', 'Oignon'], [200, 'ml', 'Crème liquide'],
    [120, 'g', 'Fromage râpé'], [1, 'cs', 'Huile d\'olive'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Cuire l\'Ebly 10 minutes à l\'eau bouillante salée, égoutter.',
    'Faire revenir l\'oignon émincé, les carottes et la courgette en petits dés 10 minutes à l\'huile.',
    'Couper le jambon en lanières et l\'ajouter aux légumes.',
    'Mélanger l\'Ebly, les légumes, le jambon et la crème. Saler et poivrer.',
    'Verser dans un plat à gratin, couvrir de fromage râpé.',
    'Enfourner 20 minutes à 200 °C jusqu\'à belle coloration.',
  ]),
  r('docs-plats-frites-patate-douce', 'Frites de patate douce au four et rillette de thon', 'four', 35, 4, [
    [900, 'g', 'Patate douce'], [2, 'cs', 'Huile d\'olive'], [1, 'cc', 'Paprika'],
    [280, 'g', 'Thon'], [150, 'g', 'Fromage blanc'], [1, 'pc', 'Citron'],
    [2, 'pc', 'Échalote'], [1, 'botte', 'Ciboulette'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four à 210 °C.',
    'Éplucher les patates douces et les tailler en bâtonnets réguliers.',
    'Les enrober d\'huile et de paprika, les étaler sans les superposer sur une plaque.',
    'Enfourner 25 à 30 minutes en remuant à mi-cuisson.',
    'Écraser le thon égoutté avec le fromage blanc, les échalotes et la ciboulette ciselées, le jus de citron.',
    'Saler, poivrer et servir les frites bien chaudes avec la rillette fraîche.',
  ]),
  r('docs-plats-gratin-poisson', 'Gratin de poisson aux légumes', 'four', 45, 4, [
    [700, 'g', 'Poisson blanc'], [3, 'pc', 'Carotte'], [1, 'pc', 'Courgette'],
    [1, 'pc', 'Poireau'], [300, 'ml', 'Crème liquide'], [120, 'g', 'Fromage râpé'],
    [1, 'pc', 'Citron'], [30, 'g', 'Beurre'], [1, 'pincée', 'Noix de muscade'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Émincer le poireau, tailler carottes et courgette en rondelles fines.',
    'Les faire fondre 12 minutes au beurre à couvert, saler et poivrer.',
    'Beurrer un plat, y répartir les légumes puis le poisson en morceaux.',
    'Arroser de crème, d\'un filet de jus de citron et râper un peu de muscade.',
    'Couvrir de fromage râpé.',
    'Enfourner 25 minutes à 190 °C, jusqu\'à ce que le gratin soit doré et le poisson cuit.',
  ]),
  r('docs-plats-gratin-riz-jambon', 'Gratin de riz jambon courgette', 'four', 40, 4, [
    [250, 'g', 'Riz'], [250, 'g', 'Jambon'], [2, 'pc', 'Courgette'],
    [1, 'pc', 'Oignon'], [250, 'ml', 'Crème liquide'], [2, 'pc', 'Oeufs'],
    [120, 'g', 'Fromage râpé'], [1, 'cs', 'Huile d\'olive'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Cuire le riz à l\'eau salée, égoutter.',
    'Faire revenir l\'oignon émincé et les courgettes en rondelles 10 minutes à l\'huile.',
    'Battre les œufs avec la crème, saler et poivrer.',
    'Mélanger le riz, les courgettes, le jambon en dés et l\'appareil aux œufs.',
    'Verser dans un plat beurré et parsemer de fromage râpé.',
    'Enfourner 25 minutes à 190 °C.',
  ]),
  r('docs-plats-hache-boeuf-wraps', 'Haché de boeuf aux légumes et ses wraps', 'viande', 25, 4, [
    [500, 'g', 'Steak haché'], [8, 'pc', 'Wraps'], [1, 'pc', 'Poivron'],
    [1, 'pc', 'Courgette'], [1, 'pc', 'Oignon'], [2, 'gousse', 'Ail'],
    [200, 'g', 'Tomate'], [100, 'g', 'Salade'], [100, 'g', 'Fromage râpé'],
    [1, 'cc', 'Cumin'], [1, 'cc', 'Paprika'], [1, 'cs', 'Huile d\'olive'],
  ], [
    'Faire revenir l\'oignon et l\'ail hachés à l\'huile.',
    'Ajouter le haché de bœuf, l\'émietter et le saisir 5 minutes.',
    'Incorporer le poivron et la courgette en petits dés, le cumin et le paprika.',
    'Ajouter les tomates concassées, laisser mijoter 8 minutes à découvert.',
    'Réchauffer les wraps 20 secondes à la poêle sèche.',
    'Garnir de haché, de salade et de fromage râpé, rouler serré et servir.',
  ]),
  r('docs-plats-hamburger-frites', 'Hamburger maison et frites de patate douce', 'viande', 40, 4, [
    [600, 'g', 'Steak haché'], [4, 'pc', 'Pain'], [800, 'g', 'Patate douce'],
    [4, 'tranche', 'Cheddar'], [2, 'pc', 'Tomate'], [100, 'g', 'Salade'],
    [1, 'pc', 'Oignon'], [2, 'cs', 'Huile d\'olive'], [2, 'cs', 'Ketchup'],
    [1, 'cs', 'Moutarde'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four à 210 °C. Tailler les patates douces en bâtonnets.',
    'Les enrober d\'huile, saler, et enfourner 25 à 30 minutes en remuant à mi-cuisson.',
    'Former quatre steaks, saler et poivrer les deux faces.',
    'Les saisir 3 à 4 minutes par face, poser une tranche de cheddar en fin de cuisson pour la faire fondre.',
    'Toaster les pains, les tartiner de ketchup et de moutarde.',
    'Monter avec salade, tomate, oignon en rondelles et le steak. Servir avec les frites.',
  ]),
  r('docs-plats-lasagne-panais-potimarron', 'Lasagne de panais et potimarron', 'four', 60, 4, [
    [12, 'pc', 'Lasagnes'], [500, 'g', 'Potimarron'], [400, 'g', 'Panais'],
    [500, 'ml', 'Lait'], [40, 'g', 'Farine'], [40, 'g', 'Beurre'],
    [120, 'g', 'Fromage râpé'], [1, 'branche', 'Thym'],
    [1, 'pincée', 'Noix de muscade'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Éplucher le potimarron et les panais, les couper en fines lamelles à l\'économe ou à la mandoline.',
    'Préparer une béchamel : fondre le beurre, ajouter la farine, puis le lait peu à peu en fouettant.',
    'Assaisonner la béchamel de sel, poivre, muscade et thym effeuillé.',
    'Dans un plat, alterner béchamel, feuilles de lasagne, rubans de potimarron, puis panais.',
    'Terminer par une couche de béchamel et le fromage râpé.',
    'Enfourner 40 minutes à 180 °C, à couvert les 25 premières minutes.',
  ]),
  r('docs-plats-lasagne-express-legumes', 'Lasagne express aux légumes', 'four', 40, 4, [
    [12, 'pc', 'Lasagnes'], [1, 'pc', 'Courgette'], [1, 'pc', 'Aubergine'],
    [1, 'pc', 'Poivron'], [1, 'pc', 'Oignon'], [700, 'g', 'Sauce tomate'],
    [250, 'g', 'Ricotta'], [120, 'g', 'Fromage râpé'], [2, 'cs', 'Huile d\'olive'],
    [1, 'cc', 'Origan'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Tailler tous les légumes en petits dés.',
    'Les faire sauter 10 minutes à feu vif dans l\'huile, saler et poivrer.',
    'Ajouter la sauce tomate et l\'origan, laisser mijoter 5 minutes.',
    'Alterner dans un plat : sauce aux légumes, feuilles de lasagne, quelques cuillères de ricotta.',
    'Finir par la sauce et le fromage râpé.',
    'Enfourner 25 minutes à 200 °C.',
  ]),
  r('docs-plats-linguine-scampis', 'Linguine scampis chorizo et mozzarella', 'poisson', 25, 4, [
    [400, 'g', 'Pâtes'], [400, 'g', 'Scampis'], [150, 'g', 'Chorizo'],
    [250, 'g', 'Mozzarella'], [200, 'g', 'Tomate'], [1, 'pc', 'Poivron'],
    [2, 'pc', 'Échalote'], [2, 'gousse', 'Ail'], [150, 'ml', 'Crème liquide'],
    [2, 'cs', 'Huile d\'olive'], [1, 'pincée', 'Piment'], [1, 'pincée', 'Sel'],
  ], [
    'Cuire les linguine al dente à l\'eau salée, réserver un verre d\'eau de cuisson.',
    'Faire rissoler le chorizo en rondelles sans matière grasse, réserver.',
    'Dans la même poêle, faire suer les échalotes, l\'ail et le poivron en lanières.',
    'Ajouter les scampis et les saisir 2 minutes par face, puis les tomates en dés et la crème.',
    'Verser les pâtes égouttées dans la sauce avec un peu d\'eau de cuisson, mélanger vivement 1 minute.',
    'Hors du feu, ajouter la mozzarella déchirée à la main et une pincée de piment.',
  ]),
  r('docs-plats-oeuf-pdt-carottes', 'Oeuf au plat carottes et courgettes', 'rapide', 25, 4, [
    [8, 'pc', 'Oeufs'], [600, 'g', 'Pomme de terre'], [3, 'pc', 'Carotte'],
    [2, 'pc', 'Courgette'], [1, 'pc', 'Oignon'], [2, 'cs', 'Huile d\'olive'],
    [1, 'branche', 'Thym'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Couper les pommes de terre en dés et les cuire 12 minutes à l\'eau salée.',
    'Faire revenir l\'oignon émincé, les carottes et les courgettes en rondelles 10 minutes à l\'huile.',
    'Ajouter les pommes de terre égouttées et le thym, faire dorer 5 minutes.',
    'Creuser huit puits dans la poêlée et y casser les œufs.',
    'Couvrir et cuire 4 minutes, jusqu\'à ce que le blanc soit pris et le jaune coulant.',
    'Saler, poivrer et servir directement dans la poêle.',
  ]),
  r('docs-plats-oeufs-brouilles', 'Oeufs brouillés aux légumes', 'rapide', 15, 4, [
    [8, 'pc', 'Oeufs'], [1, 'pc', 'Courgette'], [1, 'pc', 'Poivron'],
    [150, 'g', 'Champignons de Paris'], [1, 'pc', 'Oignon'], [30, 'g', 'Beurre'],
    [2, 'cs', 'Crème liquide'], [1, 'botte', 'Ciboulette'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Tailler tous les légumes en petits dés.',
    'Les faire sauter 8 minutes à feu vif dans la moitié du beurre, saler et poivrer. Réserver.',
    'Battre les œufs avec la crème.',
    'Les verser dans la poêle avec le reste de beurre, à feu doux, en remuant sans arrêt.',
    'Quand les œufs sont crémeux, retirer du feu et incorporer les légumes.',
    'Parsemer de ciboulette ciselée et servir immédiatement.',
  ]),
  r('docs-plats-paupiette-poulet', 'Paupiette de poulet au jambon et olives', 'volaille', 40, 4, [
    [4, 'pc', 'Blanc de poulet'], [4, 'tranche', 'Jambon'], [100, 'g', 'Olives'],
    [1, 'pc', 'Oignon'], [200, 'ml', 'Vin blanc'], [200, 'ml', 'Crème liquide'],
    [200, 'g', 'Tomate'], [2, 'cs', 'Huile d\'olive'], [1, 'branche', 'Thym'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Aplatir les blancs de poulet entre deux feuilles de papier cuisson.',
    'Poser sur chacun une tranche de jambon et quelques olives, rouler serré et ficeler.',
    'Faire dorer les paupiettes sur toutes les faces dans l\'huile, réserver.',
    'Faire suer l\'oignon émincé, déglacer au vin blanc et laisser réduire de moitié.',
    'Ajouter les tomates en dés, le thym et la crème, remettre les paupiettes.',
    'Couvrir et laisser mijoter 25 minutes. Retirer la ficelle avant de servir.',
  ]),
  r('docs-plats-pizza-equilibree', 'Pizza équilibrée faite maison', 'four', 30, 4, [
    [1, 'pc', 'Pâte à pizza'], [200, 'g', 'Sauce tomate'], [200, 'g', 'Mozzarella'],
    [1, 'pc', 'Courgette'], [1, 'pc', 'Poivron'], [150, 'g', 'Champignons de Paris'],
    [150, 'g', 'Blanc de poulet'], [50, 'g', 'Roquette'], [1, 'cs', 'Huile d\'olive'],
    [1, 'cc', 'Origan'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four à 240 °C avec la plaque à l\'intérieur.',
    'Étaler la pâte, la napper de sauce tomate en laissant un bord libre.',
    'Répartir le poulet cuit émincé, la courgette en fines rondelles, le poivron et les champignons.',
    'Ajouter la mozzarella égouttée, l\'origan et un filet d\'huile.',
    'Enfourner 12 à 15 minutes, jusqu\'à ce que le bord soit doré.',
    'À la sortie du four, parsemer de roquette fraîche et poivrer.',
  ]),
  r('docs-plats-plumes-chef', 'Plumes du chef', 'rapide', 25, 4, [
    [400, 'g', 'Penne'], [200, 'g', 'Jambon'], [200, 'g', 'Champignons de Paris'],
    [1, 'pc', 'Oignon'], [250, 'ml', 'Crème liquide'], [80, 'g', 'Parmesan'],
    [100, 'ml', 'Vin blanc'], [1, 'cs', 'Huile d\'olive'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Cuire les pennes al dente à l\'eau salée.',
    'Faire revenir l\'oignon émincé et les champignons en lamelles à l\'huile, jusqu\'à évaporation de l\'eau.',
    'Ajouter le jambon en lanières et faire revenir 2 minutes.',
    'Déglacer au vin blanc et laisser réduire presque à sec.',
    'Verser la crème, laisser épaissir 3 minutes, saler et poivrer.',
    'Mélanger avec les pâtes égouttées et le parmesan râpé.',
  ]),
  r('docs-plats-poisson-pane-avoine', 'Poisson blanc pané aux flocons d\'avoine', 'poisson', 25, 4, [
    [700, 'g', 'Poisson blanc'], [120, 'g', 'Flocons d\'avoine'], [2, 'pc', 'Oeufs'],
    [50, 'g', 'Farine'], [1, 'pc', 'Citron'], [2, 'cs', 'Huile d\'olive'],
    [1, 'cc', 'Paprika'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Mixer grossièrement les flocons d\'avoine avec le paprika, le sel et le poivre.',
    'Préparer trois assiettes : farine, œufs battus, flocons assaisonnés.',
    'Passer chaque morceau de poisson dans la farine, puis l\'œuf, puis les flocons en pressant bien.',
    'Chauffer l\'huile dans une poêle et dorer 3 à 4 minutes par face.',
    'Égoutter sur du papier absorbant.',
    'Servir avec des quartiers de citron.',
  ]),
  r('docs-plats-poivrons-farcis', 'Poivrons farcis au poulet courgette semoule et coulis de tomates', 'volaille', 45, 4, [
    [4, 'pc', 'Poivron'], [400, 'g', 'Blanc de poulet'], [150, 'g', 'Semoule'],
    [1, 'pc', 'Courgette'], [1, 'pc', 'Oignon'], [2, 'gousse', 'Ail'],
    [500, 'g', 'Sauce tomate'], [80, 'g', 'Fromage râpé'], [2, 'cs', 'Huile d\'olive'],
    [1, 'cc', 'Cumin'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Couvrir la semoule d\'eau bouillante salée, laisser gonfler 5 minutes puis l\'égrainer.',
    'Couper les poivrons en deux dans la longueur et les épépiner.',
    'Hacher le poulet et le faire revenir avec l\'oignon, l\'ail et la courgette en dés.',
    'Ajouter le cumin, saler, poivrer, puis mélanger à la semoule.',
    'Verser un fond de coulis dans un plat, y déposer les demi-poivrons garnis de farce.',
    'Parsemer de fromage râpé et enfourner 30 minutes à 190 °C.',
  ]),
  r('docs-plats-poelee-pdt-bacon', 'Poêlée de pommes de terre bacon oeufs et petits légumes', 'rapide', 30, 4, [
    [800, 'g', 'Pomme de terre'], [200, 'g', 'Lardons'], [4, 'pc', 'Oeufs'],
    [200, 'g', 'Petits pois'], [2, 'pc', 'Carotte'], [1, 'pc', 'Oignon'],
    [2, 'cs', 'Huile d\'olive'], [1, 'branche', 'Persil'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Couper les pommes de terre en dés, les précuire 10 minutes à l\'eau salée puis les égoutter.',
    'Faire rissoler les lardons sans matière grasse, les réserver.',
    'Dorer les pommes de terre 10 minutes dans l\'huile avec l\'oignon et les carottes en dés.',
    'Ajouter les petits pois et les lardons, poursuivre 5 minutes.',
    'Creuser quatre puits, y casser les œufs, couvrir et cuire 4 minutes.',
    'Parsemer de persil, saler et poivrer.',
  ]),
  r('docs-plats-pates-brioches-choco', 'Pâtes brioches aux pépites de chocolat', 'autres', 120, 8, [
    [500, 'g', 'Farine'], [200, 'ml', 'Lait'], [2, 'pc', 'Oeufs'],
    [100, 'g', 'Beurre'], [80, 'g', 'Sucre'], [150, 'g', 'Chocolat noir'],
    [11, 'g', 'Levure'], [1, 'pincée', 'Sel'],
  ], [
    'Tiédir le lait et y délayer la levure avec une cuillère de sucre. Laisser mousser 10 minutes.',
    'Pétrir la farine, le sucre, le sel, les œufs et le lait levuré pendant 10 minutes.',
    'Incorporer le beurre mou en morceaux et pétrir encore 5 minutes, jusqu\'à ce que la pâte se décolle.',
    'Ajouter les pépites de chocolat, couvrir et laisser lever 1 h 30 à température ambiante.',
    'Dégazer, façonner des boules et les déposer dans un moule beurré. Laisser lever 30 minutes.',
    'Dorer au jaune d\'œuf et enfourner 25 à 30 minutes à 180 °C.',
  ]),
  r('docs-plats-pates-complètes-scampis', 'Pâtes complètes aux légumes et aux scampis', 'poisson', 25, 4, [
    [400, 'g', 'Pâtes'], [400, 'g', 'Scampis'], [1, 'pc', 'Courgette'],
    [1, 'pc', 'Poivron'], [200, 'g', 'Tomate'], [2, 'gousse', 'Ail'],
    [1, 'pc', 'Citron'], [3, 'cs', 'Huile d\'olive'], [1, 'branche', 'Persil'],
    [1, 'pincée', 'Piment'], [1, 'pincée', 'Sel'],
  ], [
    'Cuire les pâtes complètes al dente à l\'eau salée.',
    'Faire revenir l\'ail haché dans l\'huile, ajouter le poivron et la courgette en dés, 8 minutes.',
    'Ajouter les tomates en dés et laisser compoter 5 minutes.',
    'Saisir les scampis 2 minutes par face avec le piment.',
    'Mélanger les pâtes égouttées à la poêlée avec un filet de jus de citron.',
    'Parsemer de persil ciselé et servir.',
  ]),
  r('docs-plats-pates-brocoli-oeuf-jambon', 'Pâtes complètes brocoli oeuf et jambon bacon', 'rapide', 25, 4, [
    [400, 'g', 'Pâtes'], [500, 'g', 'Brocoli'], [4, 'pc', 'Oeufs'],
    [150, 'g', 'Lardons'], [2, 'gousse', 'Ail'], [80, 'g', 'Parmesan'],
    [2, 'cs', 'Huile d\'olive'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Cuire les œufs 9 minutes à l\'eau bouillante, les rafraîchir et les écaler.',
    'Cuire les pâtes al dente, en ajoutant les fleurettes de brocoli les 5 dernières minutes.',
    'Faire rissoler les lardons avec l\'ail haché dans l\'huile.',
    'Égoutter pâtes et brocoli en réservant un peu d\'eau de cuisson, les verser dans la poêle.',
    'Mélanger avec le parmesan et un peu d\'eau de cuisson pour lier.',
    'Servir avec les œufs coupés en deux, poivrer généreusement.',
  ]),
  r('docs-plats-pates-jambon-italien', 'Pâtes jambon italien parmesan', 'rapide', 20, 4, [
    [400, 'g', 'Pâtes'], [150, 'g', 'Jambon'], [100, 'g', 'Parmesan'],
    [200, 'ml', 'Crème liquide'], [2, 'gousse', 'Ail'], [50, 'g', 'Roquette'],
    [2, 'cs', 'Huile d\'olive'], [1, 'pincée', 'Poivre'],
  ], [
    'Cuire les pâtes al dente à l\'eau salée, réserver un peu d\'eau de cuisson.',
    'Faire blondir l\'ail haché dans l\'huile.',
    'Ajouter la crème et la moitié du parmesan, laisser épaissir 2 minutes.',
    'Verser les pâtes égouttées et mélanger avec un peu d\'eau de cuisson.',
    'Ajouter le jambon italien en lanières hors du feu, pour qu\'il reste moelleux.',
    'Servir avec le reste de parmesan, la roquette et du poivre du moulin.',
  ]),
  r('docs-plats-pates-sauce-poivrons', 'Pâtes sauce aux poivronscarottes jambon cuit de Malmedy et courgettes', 'rapide', 30, 4, [
    [400, 'g', 'Pâtes'], [2, 'pc', 'Poivron'], [2, 'pc', 'Carotte'],
    [1, 'pc', 'Courgette'], [200, 'g', 'Jambon'], [1, 'pc', 'Oignon'],
    [2, 'gousse', 'Ail'], [200, 'ml', 'Crème liquide'], [2, 'cs', 'Huile d\'olive'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Cuire les pâtes al dente à l\'eau salée.',
    'Faire revenir l\'oignon et l\'ail hachés dans l\'huile.',
    'Ajouter les poivrons et les carottes en dés, cuire 10 minutes à couvert.',
    'Ajouter la courgette en dés, poursuivre 5 minutes.',
    'Mixer la moitié des légumes avec la crème pour obtenir une sauce onctueuse, remettre en poêle.',
    'Ajouter le jambon en lanières, mélanger aux pâtes, saler et poivrer.',
  ]),
  r('docs-plats-pates-tomates-aubergine-burrata', 'Pâtes tomates aubergine et burrata', 'vege', 30, 4, [
    [400, 'g', 'Pâtes'], [1, 'pc', 'Aubergine'], [500, 'g', 'Tomate'],
    [250, 'g', 'Burrata'], [2, 'gousse', 'Ail'], [1, 'botte', 'Basilic'],
    [3, 'cs', 'Huile d\'olive'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Couper l\'aubergine en dés, la faire dorer 12 minutes à l\'huile à feu vif.',
    'Ajouter l\'ail haché et les tomates en dés, laisser compoter 10 minutes.',
    'Cuire les pâtes al dente à l\'eau salée.',
    'Mélanger les pâtes égouttées à la sauce, saler et poivrer.',
    'Dresser et déposer la burrata déchirée à la main sur les pâtes chaudes.',
    'Parsemer de basilic et arroser d\'un filet d\'huile d\'olive.',
  ]),
  r('docs-plats-peche-thon-salade', 'Pêche au thon salade de pâtes aux légumes et salade', 'rapide', 25, 4, [
    [4, 'pc', 'Pêche'], [280, 'g', 'Thon'], [250, 'g', 'Pâtes'],
    [1, 'pc', 'Poivron'], [1, 'pc', 'Concombre'], [200, 'g', 'Tomate'],
    [100, 'g', 'Salade'], [3, 'cs', 'Mayonnaise'], [2, 'cs', 'Huile d\'olive'],
    [1, 'pc', 'Citron'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Cuire les pâtes, les rafraîchir à l\'eau froide et bien les égoutter.',
    'Mélanger le thon égoutté avec la mayonnaise, un filet de citron, du sel et du poivre.',
    'Couper les pêches en deux, retirer le noyau et creuser légèrement.',
    'Garnir chaque demi-pêche du mélange au thon.',
    'Mélanger les pâtes froides avec le poivron, le concombre et les tomates en dés, l\'huile et le citron.',
    'Servir les pêches sur un lit de salade, avec la salade de pâtes à côté.',
  ]),
  r('docs-plats-quiche-legumes-mozza', 'Quiche aux légumes et à la mozzarella', 'four', 50, 4, [
    [1, 'pc', 'Pâte brisée'], [3, 'pc', 'Oeufs'], [200, 'ml', 'Crème liquide'],
    [100, 'ml', 'Lait'], [1, 'pc', 'Courgette'], [1, 'pc', 'Poivron'],
    [200, 'g', 'Tomate'], [200, 'g', 'Mozzarella'], [1, 'pc', 'Oignon'],
    [1, 'cs', 'Huile d\'olive'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four à 190 °C et foncer un moule avec la pâte. Piquer le fond.',
    'Faire revenir l\'oignon, la courgette et le poivron en dés 10 minutes à l\'huile.',
    'Battre les œufs avec la crème et le lait, saler et poivrer.',
    'Répartir les légumes égouttés sur le fond de tarte, ajouter les tomates en rondelles.',
    'Verser l\'appareil et parsemer de mozzarella en morceaux.',
    'Enfourner 35 minutes, jusqu\'à ce que la quiche soit prise et dorée.',
  ]),
  r('docs-plats-quiche-oignons-poireaux', 'Quiche oignons poireaux et allumettes de bacon', 'four', 50, 4, [
    [1, 'pc', 'Pâte brisée'], [3, 'pc', 'Oeufs'], [250, 'ml', 'Crème liquide'],
    [3, 'pc', 'Poireau'], [2, 'pc', 'Oignon'], [200, 'g', 'Lardons'],
    [100, 'g', 'Fromage râpé'], [20, 'g', 'Beurre'],
    [1, 'pincée', 'Noix de muscade'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four à 190 °C, foncer le moule et piquer le fond.',
    'Émincer les poireaux et les oignons, les faire fondre 15 minutes au beurre à couvert.',
    'Faire rissoler les lardons sans matière grasse, les égoutter.',
    'Battre les œufs avec la crème, la muscade, le sel et le poivre.',
    'Répartir la fondue de poireaux et les lardons sur la pâte, verser l\'appareil.',
    'Parsemer de fromage râpé et enfourner 35 minutes.',
  ]),
  r('docs-plats-quinoa-legumes-ete', 'Quinoa aux légumes d\'été', 'vege', 30, 4, [
    [250, 'g', 'Quinoa'], [1, 'pc', 'Courgette'], [1, 'pc', 'Aubergine'],
    [1, 'pc', 'Poivron'], [200, 'g', 'Tomate'], [1, 'pc', 'Oignon'],
    [2, 'gousse', 'Ail'], [100, 'g', 'Feta'], [3, 'cs', 'Huile d\'olive'],
    [1, 'botte', 'Basilic'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Rincer le quinoa et le cuire 12 minutes à l\'eau salée, puis l\'égrainer.',
    'Tailler courgette, aubergine et poivron en dés réguliers.',
    'Les faire sauter à feu vif dans l\'huile avec l\'oignon et l\'ail, 12 minutes.',
    'Ajouter les tomates en dés en fin de cuisson, saler et poivrer.',
    'Mélanger les légumes au quinoa.',
    'Parsemer de feta émiettée et de basilic ciselé, servir tiède ou froid.',
  ]),
  r('docs-plats-quinoa-mais-haricots', 'Quinoa maïs et haricots rouges', 'vege', 25, 4, [
    [250, 'g', 'Quinoa'], [400, 'g', 'Haricots rouges'], [300, 'g', 'Maïs'],
    [1, 'pc', 'Poivron'], [1, 'pc', 'Oignon'], [2, 'gousse', 'Ail'],
    [200, 'g', 'Tomate'], [1, 'pc', 'Citron vert'], [2, 'cs', 'Huile d\'olive'],
    [1, 'cc', 'Cumin'], [1, 'cc', 'Paprika'], [1, 'botte', 'Coriandre'],
  ], [
    'Cuire le quinoa 12 minutes à l\'eau salée, égoutter et laisser tiédir.',
    'Faire revenir l\'oignon, l\'ail et le poivron en dés dans l\'huile, 8 minutes.',
    'Ajouter le cumin et le paprika, puis les haricots rouges rincés et le maïs égoutté.',
    'Réchauffer 5 minutes en mélangeant, ajouter les tomates en dés.',
    'Réunir avec le quinoa, arroser de jus de citron vert.',
    'Parsemer de coriandre ciselée et servir.',
  ]),
  r('docs-plats-riz-basmati-saumon', 'Riz basmati au saumon pois gourmand et lait de coco', 'poisson', 30, 4, [
    [250, 'g', 'Riz'], [600, 'g', 'Saumon'], [300, 'g', 'Pois gourmands'],
    [400, 'ml', 'Lait de coco'], [1, 'pc', 'Oignon'], [2, 'gousse', 'Ail'],
    [20, 'g', 'Gingembre'], [1, 'pc', 'Citron vert'], [1, 'cs', 'Huile d\'olive'],
    [1, 'cc', 'Curry'], [1, 'pincée', 'Sel'],
  ], [
    'Rincer le riz basmati et le cuire à l\'eau salée, puis le réserver au chaud.',
    'Faire revenir l\'oignon, l\'ail et le gingembre hachés dans l\'huile.',
    'Ajouter le curry, puis verser le lait de coco et porter à frémissement.',
    'Ajouter les pois gourmands et laisser cuire 5 minutes.',
    'Déposer le saumon en gros cubes, couvrir et pocher 6 à 8 minutes à feu doux.',
    'Arroser de jus de citron vert et servir sur le riz.',
  ]),
  r('docs-plats-salade-ete', 'Salade d\'été', 'vege', 20, 4, [
    [200, 'g', 'Salade'], [300, 'g', 'Tomate'], [1, 'pc', 'Concombre'],
    [1, 'pc', 'Poivron'], [150, 'g', 'Feta'], [100, 'g', 'Olives'],
    [1, 'pc', 'Oignon'], [4, 'cs', 'Huile d\'olive'], [2, 'cs', 'Vinaigre balsamique'],
    [1, 'botte', 'Basilic'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Laver et essorer la salade, la disposer dans un grand saladier.',
    'Couper les tomates en quartiers, le concombre en demi-rondelles, le poivron en lanières.',
    'Émincer finement l\'oignon rouge.',
    'Préparer la vinaigrette en fouettant huile, vinaigre, sel et poivre.',
    'Réunir tous les légumes, ajouter la feta en dés et les olives.',
    'Assaisonner au dernier moment et parsemer de basilic.',
  ]),
  r('docs-plats-samossas-courgette-chevre', 'Samossas courgette et chèvre', 'four', 40, 4, [
    [12, 'pc', 'Feuilles de brick'], [2, 'pc', 'Courgette'], [200, 'g', 'Chèvre'],
    [1, 'pc', 'Oignon'], [2, 'gousse', 'Ail'], [1, 'cs', 'Miel'],
    [3, 'cs', 'Huile d\'olive'], [1, 'cc', 'Cumin'], [1, 'branche', 'Menthe'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Râper les courgettes, les faire dégorger 10 minutes avec du sel puis les presser.',
    'Faire revenir l\'oignon et l\'ail hachés, ajouter les courgettes et le cumin, 8 minutes.',
    'Hors du feu, incorporer le chèvre émietté, le miel et la menthe ciselée. Poivrer.',
    'Couper les feuilles de brick en bandes, déposer une cuillère de farce à l\'extrémité.',
    'Plier en triangle en repliant successivement, badigeonner d\'huile.',
    'Enfourner 15 à 20 minutes à 200 °C, jusqu\'à ce que les samossas soient dorés.',
  ]),
  r('docs-plats-sauce-tomates-haricots', 'Sauce tomates aux haricots rouges', 'sauce', 30, 4, [
    [800, 'g', 'Tomates concassées'], [400, 'g', 'Haricots rouges'], [1, 'pc', 'Oignon'],
    [2, 'gousse', 'Ail'], [1, 'pc', 'Poivron'], [2, 'cs', 'Concentré de tomates'],
    [2, 'cs', 'Huile d\'olive'], [1, 'cc', 'Cumin'], [1, 'cc', 'Paprika'],
    [1, 'pincée', 'Piment'], [1, 'pincée', 'Sel'],
  ], [
    'Faire revenir l\'oignon et l\'ail hachés dans l\'huile jusqu\'à ce qu\'ils soient translucides.',
    'Ajouter le poivron en dés et cuire 5 minutes.',
    'Incorporer le concentré de tomates, le cumin, le paprika et le piment, torréfier 1 minute.',
    'Verser les tomates concassées, saler et laisser mijoter 15 minutes.',
    'Ajouter les haricots rouges rincés et poursuivre 10 minutes.',
    'Rectifier l\'assaisonnement. Servir avec du riz ou des pâtes.',
  ]),
  r('docs-plats-soupe-nouilles-epicee', 'Soupe de nouilles légèrement épicée', 'monde', 25, 4, [
    [250, 'g', 'Nouilles de riz'], [1, 'l', 'Bouillon de volaille'], [300, 'g', 'Blanc de poulet'],
    [2, 'pc', 'Carotte'], [150, 'g', 'Champignons de Paris'], [100, 'g', 'Germes de soja'],
    [20, 'g', 'Gingembre'], [2, 'gousse', 'Ail'], [3, 'cs', 'Sauce soja'],
    [1, 'cs', 'Huile de sésame'], [1, 'pc', 'Citron vert'], [1, 'pincée', 'Piment'],
    [1, 'botte', 'Coriandre'],
  ], [
    'Faire chauffer l\'huile de sésame, y faire revenir l\'ail et le gingembre hachés.',
    'Verser le bouillon, ajouter la sauce soja et le piment, porter à frémissement.',
    'Ajouter les carottes en julienne et les champignons émincés, cuire 5 minutes.',
    'Pocher le poulet émincé 6 minutes dans le bouillon.',
    'Cuire les nouilles de riz selon le paquet et les répartir dans les bols.',
    'Verser le bouillon chaud, ajouter les germes de soja, la coriandre et un trait de citron vert.',
  ]),
  r('docs-plats-tarte-oignons-poivrons-feta', 'Tarte oignons poivrons feta et pois chiches', 'four', 50, 4, [
    [1, 'pc', 'Pâte brisée'], [3, 'pc', 'Oignon'], [2, 'pc', 'Poivron'],
    [200, 'g', 'Feta'], [250, 'g', 'Pois chiches'], [2, 'pc', 'Oeufs'],
    [150, 'ml', 'Crème liquide'], [2, 'cs', 'Huile d\'olive'],
    [1, 'cc', 'Origan'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four à 190 °C, foncer le moule avec la pâte et piquer le fond.',
    'Émincer les oignons et les faire confire 20 minutes à feu doux dans l\'huile.',
    'Ajouter les poivrons en lanières et poursuivre 10 minutes.',
    'Battre les œufs avec la crème, l\'origan, le sel et le poivre.',
    'Répartir la fondue d\'oignons, les pois chiches rincés et la feta émiettée sur la pâte.',
    'Verser l\'appareil et enfourner 30 minutes.',
  ]),
  r('docs-plats-tarte-salee-epinards-poivron-lieu', 'Tarte salée épinards poivron et lieu jaune', 'four', 50, 4, [
    [1, 'pc', 'Pâte brisée'], [400, 'g', 'Lieu noir'], [400, 'g', 'Épinards'],
    [1, 'pc', 'Poivron'], [3, 'pc', 'Oeufs'], [200, 'ml', 'Crème liquide'],
    [1, 'pc', 'Oignon'], [80, 'g', 'Fromage râpé'], [1, 'cs', 'Huile d\'olive'],
    [1, 'pincée', 'Noix de muscade'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four à 190 °C, foncer le moule et piquer le fond.',
    'Faire revenir l\'oignon et le poivron en dés, ajouter les épinards et laisser rendre l\'eau.',
    'Bien égoutter la garniture pour éviter que la tarte ne détrempe.',
    'Battre les œufs avec la crème, la muscade, le sel et le poivre.',
    'Répartir les légumes et le lieu jaune en morceaux sur la pâte, verser l\'appareil.',
    'Parsemer de fromage râpé et enfourner 35 minutes.',
  ]),
  r('docs-plats-tartiflette', 'Tartiflette plus ou moins légère', 'four', 60, 4, [
    [1, 'kg', 'Pomme de terre'], [400, 'g', 'Reblochon'], [200, 'g', 'Lardons'],
    [3, 'pc', 'Oignon'], [150, 'ml', 'Vin blanc'], [150, 'ml', 'Fromage blanc'],
    [1, 'cs', 'Huile d\'olive'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Cuire les pommes de terre 20 minutes à l\'eau salée, les éplucher et les couper en rondelles.',
    'Faire rissoler les lardons, les égoutter pour retirer l\'excès de gras.',
    'Faire fondre les oignons émincés dans l\'huile, déglacer au vin blanc et laisser réduire.',
    'Mélanger pommes de terre, oignons et lardons avec le fromage blanc pour alléger la liaison.',
    'Verser dans un plat, poser le reblochon coupé en deux dans l\'épaisseur, croûte vers le haut.',
    'Enfourner 25 minutes à 200 °C, jusqu\'à ce que le fromage soit fondu et doré.',
  ]),
  r('docs-plats-tomate-crevettes', 'Tomate crevettes salade de pâtes froides et salade aux graines oléagineuses', 'poisson', 30, 4, [
    [4, 'pc', 'Tomate'], [300, 'g', 'Crevettes'], [250, 'g', 'Pâtes'],
    [4, 'cs', 'Mayonnaise'], [1, 'pc', 'Citron'], [150, 'g', 'Salade'],
    [1, 'pc', 'Concombre'], [50, 'g', 'Noix'], [30, 'g', 'Amandes'],
    [3, 'cs', 'Huile d\'olive'], [1, 'branche', 'Persil'], [1, 'pincée', 'Poivre'],
  ], [
    'Cuire les pâtes, les rafraîchir et bien les égoutter.',
    'Mélanger les crevettes avec la mayonnaise, le jus de citron et le persil ciselé.',
    'Évider les tomates après avoir découpé un chapeau, les saler et les retourner pour les égoutter.',
    'Garnir les tomates du mélange aux crevettes.',
    'Assaisonner les pâtes froides avec le concombre en dés, l\'huile et un filet de citron.',
    'Servir avec la salade parsemée de noix et d\'amandes concassées.',
  ]),
  r('docs-plats-tortiglioni-champignons', 'Tortiglioni sauce légère aux champignons', 'rapide', 25, 4, [
    [400, 'g', 'Pâtes'], [500, 'g', 'Champignons de Paris'], [2, 'pc', 'Échalote'],
    [2, 'gousse', 'Ail'], [200, 'ml', 'Fromage blanc'], [100, 'ml', 'Bouillon de légumes'],
    [60, 'g', 'Parmesan'], [1, 'cs', 'Huile d\'olive'], [1, 'branche', 'Persil'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Cuire les tortiglioni al dente à l\'eau salée, réserver un peu d\'eau de cuisson.',
    'Émincer les champignons et les faire sauter à feu vif jusqu\'à évaporation de l\'eau.',
    'Ajouter les échalotes et l\'ail hachés, cuire 3 minutes.',
    'Verser le bouillon et laisser réduire de moitié.',
    'Hors du feu, incorporer le fromage blanc pour une sauce crémeuse sans crème.',
    'Mélanger aux pâtes, ajouter le parmesan et le persil, poivrer généreusement.',
  ]),
  r('docs-plats-wraps', 'Wraps maison', 'rapide', 20, 4, [
    [8, 'pc', 'Wraps'], [400, 'g', 'Blanc de poulet'], [150, 'g', 'Salade'],
    [2, 'pc', 'Tomate'], [1, 'pc', 'Concombre'], [1, 'pc', 'Avocat'],
    [150, 'g', 'Fromage blanc'], [1, 'pc', 'Citron'], [1, 'cs', 'Huile d\'olive'],
    [1, 'cc', 'Paprika'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Émincer le poulet, l\'assaisonner de paprika, sel et poivre, puis le saisir 6 minutes à l\'huile.',
    'Mélanger le fromage blanc avec le jus de citron pour obtenir une sauce légère.',
    'Réchauffer les galettes 20 secondes à la poêle sèche pour les assouplir.',
    'Tartiner chaque galette de sauce en laissant les bords libres.',
    'Garnir de salade, tomate, concombre, avocat en lamelles et poulet.',
    'Rouler serré en repliant les côtés, couper en deux en biais.',
  ]),

  // ============================ DESSERTS ============================
  r('docs-desserts-cantuchini', 'Cantuchini', 'dessert', 50, 8, [
    [300, 'g', 'Farine'], [200, 'g', 'Sucre'], [200, 'g', 'Amandes'],
    [2, 'pc', 'Oeufs'], [2, 'pc', 'Jaune d\'oeuf'], [1, 'cc', 'Levure chimique'],
    [1, 'pc', 'Citron'], [1, 'cc', 'Vanille'], [1, 'pincée', 'Sel'],
  ], [
    'Préchauffer le four à 170 °C.',
    'Mélanger la farine, le sucre, la levure, le sel et le zeste de citron râpé.',
    'Ajouter les œufs, les jaunes et la vanille, pétrir jusqu\'à obtenir une pâte homogène.',
    'Incorporer les amandes entières non mondées.',
    'Former deux boudins aplatis sur une plaque, enfourner 25 minutes.',
    'Couper les boudins encore tièdes en tranches biseautées, puis remettre 10 minutes à 160 °C pour les sécher.',
  ]),
  r('docs-desserts-clafoutis-framboises-myrtilles', 'Clafoutis aux framboises et myrtilles', 'dessert', 45, 6, [
    [250, 'g', 'Framboises'], [200, 'g', 'Myrtilles'], [3, 'pc', 'Oeufs'],
    [100, 'g', 'Sucre'], [80, 'g', 'Farine'], [400, 'ml', 'Lait'],
    [20, 'g', 'Beurre'], [1, 'cc', 'Vanille'], [1, 'pincée', 'Sel'],
  ], [
    'Préchauffer le four à 180 °C et beurrer un plat à gratin.',
    'Fouetter les œufs avec le sucre jusqu\'à ce que le mélange blanchisse.',
    'Ajouter la farine tamisée et le sel, puis délayer avec le lait et la vanille.',
    'Répartir les framboises et les myrtilles dans le plat.',
    'Verser la pâte délicatement par-dessus.',
    'Enfourner 35 minutes, jusqu\'à ce que le clafoutis soit pris et doré. Servir tiède.',
  ]),
  r('docs-desserts-flans-legumes', 'Flans aux légumes', 'autres', 45, 4, [
    [400, 'g', 'Courgette'], [3, 'pc', 'Carotte'], [200, 'g', 'Brocoli'],
    [4, 'pc', 'Oeufs'], [250, 'ml', 'Crème liquide'], [80, 'g', 'Fromage râpé'],
    [20, 'g', 'Beurre'], [1, 'pincée', 'Noix de muscade'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four à 170 °C et beurrer des ramequins.',
    'Cuire séparément les légumes à la vapeur jusqu\'à ce qu\'ils soient tendres.',
    'Mixer chaque légume à part pour garder trois purées distinctes.',
    'Battre les œufs avec la crème, la muscade, le sel et le poivre, puis répartir sur les purées.',
    'Verser dans les ramequins et parsemer de fromage râpé.',
    'Cuire 30 minutes au bain-marie, jusqu\'à ce que les flans soient pris.',
  ]),
  r('docs-desserts-gateau-choco-laurie', 'Gâteau au chocolat de Laurie', 'dessert', 40, 8, [
    [200, 'g', 'Chocolat noir'], [150, 'g', 'Beurre'], [150, 'g', 'Sucre'],
    [4, 'pc', 'Oeufs'], [80, 'g', 'Farine'], [1, 'cc', 'Levure chimique'],
    [1, 'pincée', 'Sel'],
  ], [
    'Préchauffer le four à 180 °C et beurrer un moule.',
    'Faire fondre le chocolat avec le beurre au bain-marie, puis lisser.',
    'Fouetter les œufs avec le sucre jusqu\'à ce que le mélange blanchisse.',
    'Incorporer le chocolat fondu tiède, puis la farine, la levure et le sel.',
    'Verser dans le moule et enfourner 22 à 25 minutes : le centre doit rester légèrement fondant.',
    'Laisser tiédir avant de démouler.',
  ]),
  r('docs-desserts-gateau-choco-domi', 'Gâteau au chocolat domi', 'dessert', 45, 8, [
    [200, 'g', 'Chocolat noir'], [125, 'g', 'Beurre'], [125, 'g', 'Sucre'],
    [3, 'pc', 'Oeufs'], [100, 'g', 'Farine'], [100, 'ml', 'Crème liquide'],
    [1, 'cc', 'Levure chimique'], [1, 'cs', 'Cacao'], [1, 'pincée', 'Sel'],
  ], [
    'Préchauffer le four à 180 °C et chemiser un moule de papier cuisson.',
    'Faire fondre doucement le chocolat avec le beurre et la crème.',
    'Séparer les blancs des jaunes. Blanchir les jaunes avec le sucre.',
    'Ajouter le chocolat fondu, puis la farine, le cacao, la levure et le sel.',
    'Monter les blancs en neige ferme et les incorporer délicatement à la maryse.',
    'Enfourner 30 minutes. Vérifier la cuisson : la lame doit ressortir légèrement humide.',
  ]),
  r('docs-desserts-gateau-flocons-avoine', 'Gâteau aux flocons d\'avoine pomme de terre cannelle', 'dessert', 50, 8, [
    [200, 'g', 'Flocons d\'avoine'], [300, 'g', 'Pomme'], [200, 'g', 'Pomme de terre'],
    [3, 'pc', 'Oeufs'], [80, 'g', 'Sucre roux'], [150, 'ml', 'Lait'],
    [1, 'cs', 'Cannelle'], [1, 'cc', 'Levure chimique'], [1, 'pincée', 'Sel'],
  ], [
    'Cuire les pommes de terre à l\'eau, les éplucher et les écraser en purée fine. Laisser refroidir.',
    'Préchauffer le four à 180 °C et chemiser un moule.',
    'Mélanger les flocons d\'avoine, la cannelle, la levure et le sel.',
    'Battre les œufs avec le sucre roux, ajouter le lait puis la purée de pommes de terre.',
    'Réunir les deux préparations et incorporer les pommes râpées.',
    'Verser dans le moule et enfourner 40 minutes. Laisser refroidir avant de démouler.',
  ]),
  r('docs-desserts-pudding-vanille', 'Pudding à la vanille', 'dessert', 20, 4, [
    [750, 'ml', 'Lait'], [80, 'g', 'Sucre'], [50, 'g', 'Maïzena'],
    [3, 'pc', 'Jaune d\'oeuf'], [1, 'cc', 'Vanille'], [20, 'g', 'Beurre'],
    [1, 'pincée', 'Sel'],
  ], [
    'Faire chauffer 600 ml de lait avec la vanille et la moitié du sucre.',
    'Délayer la maïzena dans le lait froid restant, ajouter les jaunes et le reste de sucre.',
    'Verser le lait chaud sur le mélange en fouettant, puis remettre le tout dans la casserole.',
    'Cuire à feu moyen sans cesser de fouetter jusqu\'à épaississement, environ 3 minutes.',
    'Hors du feu, incorporer le beurre et une pincée de sel.',
    'Répartir dans des ramequins, filmer au contact et réfrigérer au moins 3 heures.',
  ]),
  r('docs-desserts-riz-au-lait', 'Riz au lait', 'dessert', 40, 4, [
    [200, 'g', 'Riz arborio'], [1, 'l', 'Lait entier'], [100, 'g', 'Sucre'],
    [1, 'cc', 'Vanille'], [20, 'g', 'Beurre'], [1, 'pincée', 'Sel'],
  ], [
    'Blanchir le riz 3 minutes à l\'eau bouillante, puis l\'égoutter.',
    'Porter le lait à frémissement avec la vanille et le sel.',
    'Ajouter le riz et cuire 30 minutes à feu très doux, en remuant régulièrement.',
    'Incorporer le sucre à mi-cuisson pour ne pas durcir les grains.',
    'Quand le riz est fondant et le lait presque absorbé, ajouter le beurre hors du feu.',
    'Servir tiède ou froid ; le riz épaissit encore en refroidissant.',
  ]),
  r('docs-desserts-torta-paradiso', 'Torta Paradiso', 'dessert', 55, 8, [
    [200, 'g', 'Beurre'], [200, 'g', 'Sucre'], [4, 'pc', 'Oeufs'],
    [125, 'g', 'Farine'], [125, 'g', 'Fécule'], [1, 'pc', 'Citron'],
    [1, 'cc', 'Vanille'], [1, 'cc', 'Levure chimique'], [1, 'pincée', 'Sel'],
    [2, 'cs', 'Sucre glace'],
  ], [
    'Sortir le beurre à l\'avance : il doit être très mou. Préchauffer le four à 170 °C.',
    'Travailler le beurre en pommade avec le sucre jusqu\'à obtenir un mélange clair et aérien.',
    'Ajouter les œufs un à un, en fouettant bien entre chaque.',
    'Parfumer avec le zeste de citron râpé et la vanille.',
    'Incorporer la farine, la fécule, la levure et le sel tamisés ensemble.',
    'Verser dans un moule beurré, enfourner 40 minutes et saupoudrer de sucre glace une fois refroidi.',
  ]),

  // ============================ APÉRO ============================
  r('docs-apero-boulettes-flocons-courgette', 'Boulettes apéritives aux flocons d\'avoine et à la courgette', 'apero', 35, 4, [
    [2, 'pc', 'Courgette'], [150, 'g', 'Flocons d\'avoine'], [2, 'pc', 'Oeufs'],
    [80, 'g', 'Parmesan'], [1, 'pc', 'Oignon'], [2, 'gousse', 'Ail'],
    [2, 'cs', 'Huile d\'olive'], [1, 'branche', 'Persil'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Râper les courgettes, les saler et les laisser dégorger 15 minutes, puis les presser fortement.',
    'Mélanger les courgettes avec les flocons d\'avoine, les œufs et le parmesan râpé.',
    'Ajouter l\'oignon et l\'ail finement hachés, le persil ciselé, le poivre.',
    'Laisser reposer 10 minutes pour que les flocons absorbent l\'humidité.',
    'Former des boulettes de la taille d\'une noix et les déposer sur une plaque huilée.',
    'Enfourner 20 minutes à 200 °C en les retournant à mi-cuisson.',
  ]),
  r('docs-apero-pois-chiches-grilles', 'Pois chiches grillés pour l\'apéro', 'apero', 40, 4, [
    [500, 'g', 'Pois chiches'], [2, 'cs', 'Huile d\'olive'], [1, 'cc', 'Paprika'],
    [1, 'cc', 'Cumin'], [1, 'pincée', 'Piment'], [1, 'pincée', 'Sel'],
  ], [
    'Préchauffer le four à 200 °C.',
    'Rincer et égoutter les pois chiches, puis les sécher soigneusement dans un torchon.',
    'Retirer les peaux qui se détachent : elles empêchent le croustillant.',
    'Les mélanger avec l\'huile, le paprika, le cumin, le piment et le sel.',
    'Les étaler en une seule couche sur une plaque.',
    'Enfourner 30 à 35 minutes en secouant la plaque toutes les 10 minutes. Servir bien croustillants.',
  ]),
  r('docs-apero-roules-courgettes-saumon', 'Roulés apéritifs de courgettes au saumon fumé', 'apero', 25, 4, [
    [2, 'pc', 'Courgette'], [200, 'g', 'Saumon'], [200, 'g', 'Fromage frais'],
    [1, 'pc', 'Citron'], [1, 'botte', 'Aneth'], [1, 'cs', 'Huile d\'olive'],
    [1, 'pincée', 'Poivre'],
  ], [
    'Tailler les courgettes en longues lanières fines à l\'économe.',
    'Les faire griller 1 minute par face à la poêle huilée, puis les laisser refroidir sur du papier absorbant.',
    'Mélanger le fromage frais avec l\'aneth ciselée, le zeste et un filet de jus de citron, et du poivre.',
    'Étaler une fine couche de ce mélange sur chaque lanière de courgette.',
    'Poser une bande de saumon fumé et rouler serré.',
    'Fixer d\'un pique et réserver au frais 30 minutes avant de servir.',
  ]),
  r('docs-apero-toasts-crevettes', 'Toasts crevettes tomates sechées', 'apero', 20, 4, [
    [12, 'tranche', 'Pain'], [300, 'g', 'Crevettes'], [100, 'g', 'Tomates séchées'],
    [150, 'g', 'Fromage frais'], [1, 'pc', 'Citron'], [1, 'gousse', 'Ail'],
    [2, 'cs', 'Huile d\'olive'], [1, 'branche', 'Basilic'], [1, 'pincée', 'Poivre'],
  ], [
    'Toaster les tranches de pain, puis les frotter légèrement avec la gousse d\'ail.',
    'Mélanger le fromage frais avec le zeste de citron et le poivre.',
    'Hacher grossièrement les tomates séchées égouttées.',
    'Tartiner les toasts de fromage frais.',
    'Répartir les crevettes décortiquées et les tomates séchées.',
    'Arroser d\'un filet d\'huile et parsemer de basilic ciselé.',
  ]),

  // ============================ EN-CAS ============================
  r('docs-encas-biscuits-fromage-blanc', 'Biscuits au fromage blanc et au yaourt nature pépites de chocolat', 'encas', 35, 8, [
    [150, 'g', 'Fromage blanc'], [125, 'g', 'Yaourt'], [250, 'g', 'Farine'],
    [80, 'g', 'Sucre'], [1, 'pc', 'Oeuf'], [120, 'g', 'Chocolat noir'],
    [1, 'cc', 'Levure chimique'], [1, 'cc', 'Vanille'], [1, 'pincée', 'Sel'],
  ], [
    'Préchauffer le four à 180 °C.',
    'Mélanger le fromage blanc, le yaourt, l\'œuf, le sucre et la vanille.',
    'Ajouter la farine, la levure et le sel, mélanger sans trop travailler la pâte.',
    'Incorporer les pépites de chocolat.',
    'Déposer des cuillerées de pâte espacées sur une plaque garnie de papier cuisson.',
    'Enfourner 15 minutes, jusqu\'à ce que les bords soient dorés. Laisser refroidir sur grille.',
  ]),
  r('docs-encas-biscuits-avoine-banane', 'Biscuits avoine banane choco', 'encas', 30, 8, [
    [3, 'pc', 'Banane'], [250, 'g', 'Flocons d\'avoine'], [100, 'g', 'Chocolat noir'],
    [50, 'g', 'Noisettes'], [2, 'cs', 'Miel'], [1, 'cc', 'Cannelle'],
    [1, 'pincée', 'Sel'],
  ], [
    'Préchauffer le four à 180 °C.',
    'Écraser les bananes bien mûres à la fourchette pour obtenir une purée.',
    'Mélanger avec les flocons d\'avoine, le miel, la cannelle et le sel.',
    'Ajouter le chocolat concassé et les noisettes grossièrement hachées.',
    'Former des petits tas aplatis sur une plaque garnie de papier cuisson.',
    'Enfourner 15 à 18 minutes. Laisser refroidir avant de décoller.',
  ]),
  r('docs-encas-cake-courgettes-chevre', 'Cake courgettes et chèvre', 'encas', 55, 6, [
    [2, 'pc', 'Courgette'], [200, 'g', 'Chèvre'], [200, 'g', 'Farine'],
    [3, 'pc', 'Oeufs'], [100, 'ml', 'Lait'], [80, 'ml', 'Huile d\'olive'],
    [1, 'cc', 'Levure chimique'], [1, 'branche', 'Menthe'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four à 180 °C et chemiser un moule à cake.',
    'Râper les courgettes, les faire dégorger avec du sel puis les presser.',
    'Battre les œufs avec le lait et l\'huile.',
    'Ajouter la farine et la levure, mélanger sans trop insister.',
    'Incorporer les courgettes, le chèvre en dés, la menthe ciselée et le poivre.',
    'Verser dans le moule et enfourner 45 minutes. Vérifier la cuisson à la lame.',
  ]),
  r('docs-encas-crunchy-muesli', 'Crunchy muesli - Granola', 'encas', 35, 8, [
    [400, 'g', 'Flocons d\'avoine'], [100, 'g', 'Amandes'], [80, 'g', 'Noisettes'],
    [80, 'g', 'Miel'], [60, 'ml', 'Huile de tournesol'], [80, 'g', 'Raisins secs'],
    [1, 'cc', 'Cannelle'], [1, 'pincée', 'Sel'],
  ], [
    'Préchauffer le four à 160 °C.',
    'Mélanger les flocons d\'avoine, les amandes et les noisettes concassées, la cannelle et le sel.',
    'Faire tiédir le miel avec l\'huile, puis verser sur le mélange sec et bien enrober.',
    'Étaler en couche régulière sur une plaque garnie de papier cuisson.',
    'Enfourner 25 minutes en remuant toutes les 8 minutes pour une coloration homogène.',
    'Ajouter les raisins secs à la sortie du four et laisser refroidir sans remuer pour garder des amas.',
  ]),
  r('docs-encas-gaufres-banane', 'Gaufres à la banane', 'encas', 30, 4, [
    [3, 'pc', 'Banane'], [250, 'g', 'Farine'], [2, 'pc', 'Oeufs'],
    [300, 'ml', 'Lait'], [50, 'g', 'Beurre'], [40, 'g', 'Sucre'],
    [1, 'cc', 'Levure chimique'], [1, 'cc', 'Vanille'], [1, 'pincée', 'Sel'],
  ], [
    'Écraser deux bananes en purée et couper la troisième en rondelles pour le service.',
    'Faire fondre le beurre et le laisser tiédir.',
    'Fouetter les œufs avec le sucre, le lait, la vanille et la purée de banane.',
    'Ajouter la farine, la levure et le sel, mélanger jusqu\'à obtenir une pâte lisse.',
    'Incorporer le beurre fondu et laisser reposer 15 minutes.',
    'Cuire dans un gaufrier chaud 3 à 4 minutes par gaufre. Servir avec les rondelles de banane.',
  ]),
  r('docs-encas-granola-noisettes-choco', 'Granola aux noisettes et au chocolat noir', 'encas', 35, 8, [
    [350, 'g', 'Flocons d\'avoine'], [150, 'g', 'Noisettes'], [120, 'g', 'Chocolat noir'],
    [80, 'g', 'Miel'], [60, 'ml', 'Huile de tournesol'], [2, 'cs', 'Cacao'],
    [1, 'pincée', 'Sel'],
  ], [
    'Préchauffer le four à 160 °C.',
    'Concasser grossièrement les noisettes et les mélanger aux flocons d\'avoine, au cacao et au sel.',
    'Tiédir le miel avec l\'huile, verser sur le mélange sec et bien enrober.',
    'Étaler sur une plaque et enfourner 25 minutes en remuant toutes les 8 minutes.',
    'Laisser refroidir complètement sur la plaque, sans remuer.',
    'Ajouter le chocolat noir concassé une fois le granola froid, pour qu\'il ne fonde pas.',
  ]),
  r('docs-encas-minis-cakes-sales', 'Minis cakes salés courgette carottes et filet de Saxe', 'encas', 45, 6, [
    [1, 'pc', 'Courgette'], [2, 'pc', 'Carotte'], [150, 'g', 'Filet de Saxe'],
    [200, 'g', 'Farine'], [3, 'pc', 'Oeufs'], [100, 'ml', 'Lait'],
    [70, 'ml', 'Huile d\'olive'], [80, 'g', 'Fromage râpé'],
    [1, 'cc', 'Levure chimique'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four à 180 °C et garnir des empreintes à muffins de caissettes.',
    'Râper la courgette et les carottes, faire dégorger la courgette et la presser.',
    'Battre les œufs avec le lait et l\'huile.',
    'Ajouter la farine, la levure, le sel et le poivre.',
    'Incorporer les légumes râpés, le filet de Saxe coupé en petits dés et le fromage râpé.',
    'Répartir dans les empreintes et enfourner 25 minutes.',
  ]),
  r('docs-encas-muffins-choco-courgette', 'Muffins chocolat noir et courgette', 'encas', 40, 6, [
    [1, 'pc', 'Courgette'], [150, 'g', 'Chocolat noir'], [200, 'g', 'Farine'],
    [2, 'pc', 'Oeufs'], [100, 'g', 'Sucre roux'], [80, 'ml', 'Huile de tournesol'],
    [3, 'cs', 'Cacao'], [1, 'cc', 'Levure chimique'], [1, 'pincée', 'Sel'],
  ], [
    'Préchauffer le four à 180 °C.',
    'Râper finement la courgette sans la presser : son eau remplace une partie de la matière grasse.',
    'Fouetter les œufs avec le sucre roux et l\'huile.',
    'Ajouter la farine, le cacao, la levure et le sel.',
    'Incorporer la courgette râpée et le chocolat concassé.',
    'Répartir dans des moules à muffins et enfourner 25 minutes.',
  ]),

  // ============================ PETITS DÉJEUNERS ============================
  r('docs-petitdej-pancakes-yaourt', 'Pancakes au yaourt', 'petitdej', 25, 4, [
    [250, 'g', 'Yaourt'], [200, 'g', 'Farine'], [2, 'pc', 'Oeufs'],
    [2, 'cs', 'Sucre'], [1, 'cc', 'Levure chimique'], [20, 'g', 'Beurre'],
    [1, 'cc', 'Vanille'], [1, 'pincée', 'Sel'],
  ], [
    'Fouetter les œufs avec le yaourt, le sucre et la vanille.',
    'Ajouter la farine, la levure et le sel, mélanger sans insister : quelques grumeaux ne gênent pas.',
    'Laisser reposer la pâte 15 minutes.',
    'Chauffer une poêle beurrée à feu moyen.',
    'Verser une petite louche de pâte et cuire jusqu\'à ce que des bulles se forment en surface.',
    'Retourner et cuire 1 minute de plus. Réserver au chaud sous un torchon.',
  ]),
  r('docs-petitdej-pancakes-banane', 'Pancakes à la banane', 'petitdej', 25, 4, [
    [3, 'pc', 'Banane'], [200, 'g', 'Farine'], [2, 'pc', 'Oeufs'],
    [250, 'ml', 'Lait'], [1, 'cc', 'Levure chimique'], [20, 'g', 'Beurre'],
    [1, 'cc', 'Cannelle'], [1, 'pincée', 'Sel'],
  ], [
    'Écraser deux bananes bien mûres en purée.',
    'Fouetter les œufs avec le lait et la purée de banane.',
    'Ajouter la farine, la levure, la cannelle et le sel.',
    'Laisser reposer 15 minutes le temps que la levure agisse.',
    'Cuire à la poêle beurrée, une petite louche à la fois, environ 2 minutes par face.',
    'Servir avec la banane restante en rondelles.',
  ]),
  r('docs-petitdej-pancakes-compote', 'Pancakes à la compote de pommes', 'petitdej', 25, 4, [
    [250, 'g', 'Compote de pommes'], [200, 'g', 'Farine'], [2, 'pc', 'Oeufs'],
    [200, 'ml', 'Lait'], [1, 'cc', 'Levure chimique'], [1, 'cc', 'Cannelle'],
    [20, 'g', 'Beurre'], [1, 'pincée', 'Sel'],
  ], [
    'Fouetter les œufs avec le lait et la compote de pommes sans sucre ajouté.',
    'Ajouter la farine, la levure, la cannelle et le sel.',
    'Mélanger jusqu\'à obtenir une pâte homogène et laisser reposer 15 minutes.',
    'Chauffer une poêle légèrement beurrée à feu moyen.',
    'Cuire les pancakes 2 minutes par face, jusqu\'à ce qu\'ils soient dorés.',
    'La compote remplace le sucre : servir tel quel ou avec un filet de miel.',
  ]),
  r('docs-petitdej-pancakes-patate-douce', 'Pancakes à la patate douce', 'petitdej', 35, 4, [
    [400, 'g', 'Patate douce'], [180, 'g', 'Farine'], [2, 'pc', 'Oeufs'],
    [200, 'ml', 'Lait'], [1, 'cc', 'Levure chimique'], [1, 'cc', 'Cannelle'],
    [2, 'cs', 'Miel'], [20, 'g', 'Beurre'], [1, 'pincée', 'Sel'],
  ], [
    'Cuire la patate douce 20 minutes à la vapeur, puis l\'écraser en purée lisse. Laisser tiédir.',
    'Fouetter les œufs avec le lait, le miel et la purée de patate douce.',
    'Ajouter la farine, la levure, la cannelle et le sel.',
    'Laisser reposer la pâte 15 minutes.',
    'Cuire à la poêle beurrée à feu moyen, 2 à 3 minutes par face.',
    'Servir tièdes, éventuellement avec un peu de miel.',
  ]),
];

export default DOCS_RECIPES;
