// data-reelles.js — recettes transcrites depuis les documents d'origine.
//
// Ces fiches remplacent les entrées reconstituées de data-docs.js : les PDF et
// DOCX fournis ont été relus et transcrits, donc les quantités et les étapes
// sont celles des documents, plus des approximations. Les identifiants sont
// repris de data-docs.js pour que le remplacement se fasse en place et que les
// favoris, la semaine et les listes de courses déjà enregistrés y survivent.
//
// Pas de drapeau `reconstructed` ici : c'est précisément ce qui les distingue.

const r = (id, name, cat, time, portions, ingredients, steps) => ({
  id, name, cat, time, portions,
  ingredients: ingredients.map(([qty, unit, n]) => ({ qty, unit, name: n })),
  steps,
});

export const REAL_RECIPES = [
  // ============================ PLATS ============================
  r('docs-plats-bouglour-lentilles-poulet', 'Boulgour et lentilles corail, émincés de poulet, courgette et carottes', 'volaille', 30, 2, [
    [60, 'g', 'Boulgour'], [60, 'g', 'Lentilles corail'], [300, 'g', 'Blanc de poulet'],
    [5, 'pc', 'Carotte'], [1, 'pc', 'Courgette'], [1, 'pc', 'Oignon'],
    [0.5, 'pc', 'Cube de bouillon de légumes'], [1, 'cc', 'Huile d\'olive'],
    [1, 'cc', 'Curry'], [1, 'cc', 'Curcuma'], [1, 'cc', 'Herbes de Provence'],
    [1, 'botte', 'Persil'], [1, 'botte', 'Ciboulette'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Faire cuire le boulgour et les lentilles à l\'eau bouillante salée pendant 10 à 12 minutes. Ils ne doivent pas être totalement cuits.',
    'Peler les carottes et l\'oignon, les couper ainsi que la courgette.',
    'Couper le blanc de poulet en petits dés.',
    'Dans une grande poêle ou un wok, faire revenir le poulet avec une cuillère à café de matière grasse pendant 5 minutes, puis réserver.',
    'Faire cuire les oignons et les carottes 5 minutes, puis ajouter les rondelles de courgette. Assaisonner.',
    'Faire bouillir de l\'eau et y ajouter le demi-cube de bouillon.',
    'Égoutter le boulgour et les lentilles, les ajouter aux légumes. Verser le bouillon petit à petit en mélangeant, jusqu\'à absorption complète et cuisson des céréales.',
    'Ajouter les dés de poulet, mélanger et rectifier l\'assaisonnement.',
  ]),
  r('docs-plats-cabillaud-curry', 'Cabillaud aux légumes et au curry rouge', 'poisson', 20, 2, [
    [400, 'g', 'Cabillaud'], [1, 'pc', 'Courgette'], [1, 'pc', 'Poivron rouge'],
    [1, 'pc', 'Poivron orange'], [1, 'pc', 'Oignon'], [2, 'cc', 'Pâte de curry rouge'],
    [1, 'cc', 'Curry'], [200, 'ml', 'Lait de coco'], [1, 'cc', 'Huile d\'olive'],
    [1, 'botte', 'Persil'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Laver et découper les légumes en petits dés, les faire revenir dans une poêle avec une cuillère à café d\'huile d\'olive. Laisser cuire 5 minutes, saler et poivrer.',
    'Ajouter le lait de coco, la pâte de curry et le curry en poudre, mélanger et laisser cuire 5 minutes.',
    'Découper le filet de cabillaud en 4 à 6 morceaux, les déposer dans la poêle et couvrir jusqu\'à ce que le poisson soit bien cuit.',
    'Saler et poivrer le poisson, décorer de persil frais.',
    'Servir avec un féculent : riz complet, riz basmati, boulgour, quinoa ou sarrasin.',
  ]),
  r('docs-plats-conchiglioni-farcis', 'Conchiglioni farcis ricotta-épinards', 'viande', 45, 4, [
    [250, 'g', 'Conchiglioni'], [200, 'g', 'Bœuf haché'], [250, 'g', 'Ricotta'],
    [300, 'g', 'Épinard'], [300, 'ml', 'Coulis de tomate'], [1, 'pc', 'Oignon'],
    [1, 'cc', 'Huile d\'olive'], [1, 'cc', 'Herbes de Provence'], [1, 'cc', 'Paprika'],
    [1, 'cc', 'Curcuma'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Faire cuire les pâtes dans de l\'eau bouillante légèrement salée. Le sel s\'ajoute une fois l\'eau en ébullition.',
    'Préchauffer le four à 200 °C.',
    'Hacher l\'oignon et le faire revenir à la poêle avec un filet d\'huile d\'olive, avec les feuilles d\'épinards frais. Réserver.',
    'Dans la même poêle, ajouter le haché, l\'émietter à la cuillère en bois et laisser cuire quelques minutes. Ajouter la ricotta et mélanger, puis les épinards. Assaisonner.',
    'Égoutter les pâtes et les rincer rapidement sous un filet d\'eau.',
    'Tapisser le fond d\'un plat allant au four de coulis de tomate épicé selon votre convenance.',
    'Farcir les pâtes du mélange haché-ricotta-épinards en pinçant les extrémités, puis les disposer dans le plat sans les superposer.',
    'Parsemer de fromage râpé et gratiner au four à 200 °C. Version végétarienne : la même recette sans le haché.',
  ]),
  r('docs-plats-courgette-farcie-quinoa', 'Courgette farcie au quinoa', 'vege', 50, 4, [
    [4, 'pc', 'Courgette ronde'], [200, 'g', 'Quinoa'], [1, 'pc', 'Échalote'],
    [200, 'g', 'Tomate cerise'], [1, 'pc', 'Poivron'], [2, 'cs', 'Fromage frais'],
    [240, 'g', 'Allumettes de bacon'], [1, 'gousse', 'Ail'],
    [1, 'pc', 'Cube de bouillon de légumes'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four à 180 °C.',
    'Cuire le quinoa dans de l\'eau bouillante salée avec un cube de bouillon de légumes.',
    'Cuire les allumettes de bacon à la poêle (ou des dés de poulet, ou égoutter des pois chiches) et réserver.',
    'Vider la courgette et faire revenir son cœur à la poêle avec l\'échalote, le poivron et la gousse d\'ail. Laisser cuire quelques minutes puis ajouter les tomates cerises.',
    'Une fois les légumes cuits, ajouter un peu de fromage frais et épicer.',
    'Mélanger le quinoa cuit et le bacon aux légumes.',
    'Farcir les courgettes avec la préparation.',
    'Enfourner à 180 °C pendant 30 minutes environ.',
  ]),
  r('docs-plats-croque-saumon', 'Croque-monsieur au saumon', 'poisson', 15, 1, [
    [2, 'tranche', 'Pain complet'], [1, 'tranche', 'Fromage à pâte dure'],
    [1, 'tranche', 'Saumon fumé'], [1, 'poignée', 'Blanc de poireau'],
    [1, 'cc', 'Fromage frais'], [1, 'cc', 'Curcuma'], [1, 'cc', 'Thym'],
    [1, 'cc', 'Aneth'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Tartiner une tranche de pain de fromage frais, déposer la tranche de saumon fumé puis la tranche de fromage à pâte dure.',
    'Faire cuire les blancs de poireaux à la poêle sans matière grasse et assaisonner de curcuma, poivre et sel.',
    'Disposer les blancs de poireaux cuits.',
    'Assaisonner de thym, d\'aneth et de poivre, refermer avec la deuxième tranche de pain.',
    'Cuire dans la machine à croque ou à la poêle en le retournant.',
    'Accompagner d\'un bol de soupe maison ou d\'une portion de crudités.',
  ]),
  r('docs-plats-crepes-salees', 'Crêpes salées — idées de garnitures', 'vege', 20, 4, [
    [1, 'pc', 'Pâte à crêpes'], [100, 'g', 'Chèvre frais'], [1, 'pc', 'Pomme'],
    [50, 'g', 'Noix'], [200, 'g', 'Ratatouille de légumes'], [2, 'pc', 'Œuf'],
    [100, 'g', 'Jambon cuit'], [100, 'g', 'Champignon de Paris'], [2, 'pc', 'Carotte'],
    [2, 'pc', 'Poireau'], [100, 'g', 'Allumettes de bacon'], [10, 'cl', 'Crème légère'],
    [100, 'g', 'Saumon fumé'], [1, 'botte', 'Aneth'], [1, 'pc', 'Citron'],
    [100, 'g', 'Ricotta'], [100, 'g', 'Épinard'], [1, 'pc', 'Avocat'],
  ], [
    'Garniture 1 : chèvre frais, pommes et noix.',
    'Garniture 2 : ratatouille de légumes.',
    'Garniture 3 : œufs brouillés, dés de jambon et champignons.',
    'Garniture 4 : carottes, poireaux, bacon et crème légère.',
    'Garniture 5 : fromage ail et fines herbes, saumon fumé, aneth et citron.',
    'Garniture 6 : saumon fumé, poireaux et crème de soja.',
    'Garniture 7 : ricotta, épinards et jambon cuit.',
    'Garniture 8 : avocat écrasé, tomates cerises, mangue et filet de Saxe.',
  ]),
  r('docs-plats-ebly-legumes-jambon', 'Ebly, légumes et jambon au four', 'viande', 40, 4, [
    [250, 'g', 'Ebly'], [1, 'pc', 'Oignon'], [9, 'pc', 'Champignon de Paris'],
    [1, 'pc', 'Poivron'], [3, 'poignée', 'Épinard'], [0.5, 'pc', 'Courgette'],
    [5, 'pc', 'Carotte'], [10, 'pc', 'Tomate cerise'], [400, 'g', 'Jambon cuit'],
    [1, 'pc', 'Cube de bouillon de légumes'], [50, 'g', 'Fromage frais'],
    [50, 'g', 'Fromage râpé'], [1, 'cs', 'Huile d\'olive'], [1, 'cc', 'Paprika'],
    [1, 'cc', 'Curry'], [1, 'cc', 'Origan'], [1, 'cc', 'Curcuma'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four à 200 °C, couper les légumes en petits cubes et faire bouillir l\'eau.',
    'Faire revenir les légumes à la poêle avec une cuillère à soupe de matière grasse, en commençant par l\'oignon, les carottes et le poivron. Laisser cuire 4 à 5 minutes.',
    'Ajouter les champignons et la courgette, laisser cuire jusqu\'à ce que les légumes soient cuits.',
    'Au dernier moment, ajouter les tomates cerises coupées et les épinards frais. Assaisonner, ajouter le fromage frais et le jambon cuit coupé en morceaux, mélanger.',
    'Ajouter le cube de bouillon à l\'eau en ébullition et mélanger.',
    'Disposer l\'Ebly cru dans un plat allant au four, ajouter par-dessus le mélange légumes-jambon-fromage frais, puis verser le bouillon.',
    'Parsemer de fromage râpé.',
    'Enfourner 15 à 20 minutes à 200 °C : le plat est cuit une fois l\'Ebly cuit.',
  ]),
  r('docs-plats-frites-patate-douce', 'Frites de patate douce au four et rillette de thon', 'poisson', 35, 2, [
    [500, 'g', 'Patate douce'], [1, 'boîte', 'Thon au naturel'],
    [1, 'cs', 'Fromage blanc'], [1, 'cs', 'Mayonnaise'], [1, 'cs', 'Ketchup'],
    [1, 'cc', 'Huile d\'olive'], [1, 'cc', 'Herbes de Provence'], [1, 'cc', 'Origan'],
    [1, 'cc', 'Paprika'], [1, 'cc', 'Curcuma'], [1, 'cc', 'Ail en poudre'],
    [1, 'cc', 'Oignon en poudre'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four à 190-200 °C.',
    'Couper les patates douces en fines lamelles, les disposer dans un plat et les assaisonner généreusement de sel, poivre, paprika, curcuma, ail, oignon en poudre, origan et herbes de Provence.',
    'Ajouter une cuillère à café d\'huile d\'olive et mélanger.',
    'Disposer les frites sur une plaque recouverte de papier sulfurisé et cuire 20 à 30 minutes. Elles doivent être moelleuses, pas croustillantes.',
    'Préparer la rillette : égoutter et rincer le thon, le disposer dans un bol.',
    'Ajouter la mayonnaise, le fromage blanc et le ketchup, poivrer et mélanger.',
    'Accompagner de crudités au choix ou de légumes chauds.',
  ]),
  r('docs-plats-gratin-poisson', 'Gratin de poisson aux légumes', 'poisson', 45, 4, [
    [600, 'g', 'Filet de poisson blanc'], [1, 'pc', 'Courgette'], [4, 'pc', 'Tomate'],
    [1, 'pc', 'Oignon rouge'], [1, 'l', 'Bouillon de poisson'], [50, 'cl', 'Lait'],
    [2, 'cs', 'Maïzena'], [1, 'cs', 'Huile d\'olive'], [1, 'cc', 'Curcuma'],
    [1, 'cc', 'Paprika'], [1, 'botte', 'Ciboulette'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four à 180 °C. Faire revenir une dizaine de minutes la courgette et l\'oignon rouge coupés, à la poêle avec une cuillère à soupe de matière grasse.',
    'Après 5 minutes de cuisson, ajouter les tomates coupées et assaisonner.',
    'Couper le poisson en dés, le plonger 4 à 5 minutes dans le bouillon de poisson, puis l\'égoutter.',
    'Préparer la béchamel légère : porter le lait à ébullition puis ajouter la Maïzena pour épaissir. Assaisonner.',
    'Dans un plat à gratin, alterner une couche de légumes cuits et un peu de poisson, et ainsi de suite.',
    'Verser la sauce pour finir et saupoudrer d\'un peu de chapelure.',
    'Faire cuire 20 minutes. Accompagner d\'une portion de féculents.',
  ]),
  r('docs-plats-lasagne-express-legumes', 'Lasagne express aux légumes', 'vege', 40, 4, [
    [6, 'pc', 'Feuille de lasagne'], [500, 'g', 'Sauce tomate'], [150, 'g', 'Ricotta'],
    [15, 'cl', 'Crème fraîche'], [150, 'g', 'Mozzarella râpée'], [1, 'pc', 'Oignon'],
    [250, 'g', 'Champignon de Paris'], [1, 'pc', 'Poivron rouge'],
    [6, 'pc', 'Tomate cerise'], [2, 'poignée', 'Épinard'], [2, 'cs', 'Huile d\'olive'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four à 200 °C.',
    'Faire revenir l\'oignon grossièrement haché dans un peu d\'huile d\'olive, ajouter le poivron rouge émincé, les champignons tranchés et les tomates cerises.',
    'Après 5 minutes, ajouter la sauce tomate et la crème fraîche, laisser mijoter 5 minutes.',
    'Ajouter les épinards et la ricotta, mélanger jusqu\'à ce que les épinards soient cuits.',
    'Assaisonner à votre goût.',
    'Dans un plat à gratin, mettre un peu de sauce et la recouvrir d\'une ou deux feuilles de lasagne côte à côte.',
    'Recouvrir les feuilles de sauce et ajouter de la mozzarella râpée. Répéter l\'opération jusqu\'à épuisement.',
    'Terminer la dernière couche par de la sauce et une bonne dose de mozzarella, enfourner environ 20 minutes et servir bien gratiné.',
  ]),
  r('docs-plats-linguine-scampis', 'Linguine scampis, chorizo et mozzarella', 'poisson', 35, 4, [
    [500, 'g', 'Linguine'], [10, 'pc', 'Scampi'], [300, 'g', 'Chorizo'],
    [2, 'pc', 'Échalote'], [2, 'pc', 'Poivron'], [1, 'poignée', 'Tomate cerise'],
    [2, 'branche', 'Céleri'], [150, 'g', 'Champignon de Paris'],
    [1, 'pc', 'Mozzarella'], [20, 'cl', 'Crème épaisse'], [1, 'cs', 'Concentré de tomate'],
    [1, 'cc', 'Purée de piment'], [2, 'cs', 'Huile d\'olive'], [1, 'pincée', 'Poivre'],
  ], [
    'Faire chauffer l\'eau des pâtes et les cuire très al dente, 1 à 2 minutes de moins que recommandé.',
    'Faire revenir l\'échalote dans un peu d\'huile d\'olive et ajouter l\'ensemble des légumes coupés en petits morceaux.',
    'Une fois les légumes attendris, ajouter le chorizo coupé en morceaux et poursuivre la cuisson.',
    'Après quelques minutes, ajouter la crème, un peu de concentré de tomate et les scampis.',
    'Couvrir et laisser mijoter à feu doux.',
    'Arrêter la cuisson dès que les scampis sont cuits : ils vont recuire ensuite, et trop cuits ils sont moyens.',
    'Ajouter les pâtes et la mozzarella, mélanger le tout sur le feu quelques minutes.',
    'Rectifier l\'assaisonnement avec le poivre et la purée de piment.',
  ]),
  r('docs-plats-oeuf-pdt-carottes', 'Œuf au plat, carottes et courgettes', 'vege', 10, 1, [
    [1, 'pc', 'Œuf'], [1, 'pc', 'Courgette'], [2, 'pc', 'Carotte'],
    [1, 'cc', 'Huile d\'olive'], [50, 'g', 'Feta'], [1, 'cc', 'Curcuma'],
    [1, 'cc', 'Curry'], [1, 'cc', 'Paprika'], [1, 'cc', 'Oignon en poudre'],
    [1, 'botte', 'Ciboulette'], [1, 'botte', 'Persil'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Couper la courgette en fines rondelles.',
    'À l\'aide d\'un éplucheur, faire des tagliatelles de carottes.',
    'Disposer les rondelles de courgette et les tagliatelles de carotte dans une poêle avec une cuillère à café d\'huile d\'olive, assaisonner et laisser cuire 2 à 3 minutes.',
    'Rassembler les légumes dans la poêle, y faire un puits et ajouter l\'œuf, avec une pincée de sel et du poivre.',
    'Laisser cuire à couvert 2 à 3 minutes, jusqu\'à ce que le blanc soit bien cuit.',
    'Émietter un peu de feta par-dessus et accompagner d\'une portion de féculent.',
  ]),
  r('docs-plats-oeufs-brouilles', 'Œufs brouillés aux légumes', 'vege', 15, 2, [
    [4, 'pc', 'Œuf'], [1, 'poignée', 'Tomate cerise'], [2, 'pc', 'Carotte'],
    [1, 'pc', 'Poivron'], [0.5, 'pc', 'Courgette'], [5, 'cs', 'Lait'],
    [1, 'pc', 'Oignon'], [1, 'cs', 'Huile d\'olive'], [1, 'cc', 'Paprika'],
    [1, 'cc', 'Origan'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Chauffer une poêle à feu moyen-vif avec une cuillère à soupe de matière grasse liquide.',
    'Ajouter l\'oignon et les carottes, les faire cuire environ 5 minutes.',
    'Ajouter les rondelles de courgette et laisser cuire 2 à 3 minutes, puis incorporer les tomates cerises et assaisonner.',
    'Pendant ce temps, fouetter les œufs et le lait dans un bol.',
    'Une fois les légumes cuits, verser la préparation œufs-lait dans la poêle et laisser cuire à feu moyen jusqu\'à ce que les œufs soient pris mais restent crémeux.',
    'Accompagner d\'un bol de soupe et d\'une portion de féculents.',
  ]),
  r('docs-plats-paupiette-poulet', 'Paupiette de poulet au jambon et olives', 'volaille', 60, 2, [
    [4, 'pc', 'Escalope de poulet'], [4, 'tranche', 'Jambon cuit'],
    [12, 'pc', 'Olive verte'], [100, 'g', 'Allumettes de bacon'],
    [100, 'ml', 'Coulis de tomate'], [50, 'ml', 'Vin blanc'], [0.5, 'pc', 'Oignon'],
    [1, 'cs', 'Huile d\'olive'], [0.5, 'branche', 'Thym'], [1, 'pc', 'Feuille de laurier'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préparer la sauce : faire revenir à la poêle l\'oignon émincé et les allumettes de bacon, juste pour les dorer.',
    'Déglacer au vin blanc et, après 2 à 3 minutes, ajouter le coulis de tomate, le thym, le laurier et le poivre.',
    'Faire mijoter la sauce environ 30 minutes à feu doux. Si elle est trop acide, ajouter un demi-sucre.',
    'Pendant que la sauce mijote, déposer une tranche de jambon sur chaque escalope, disposer 2 à 3 olives, enrouler le tout et maintenir avec des pics ou de la ficelle de cuisine.',
    'Faire dorer les paupiettes à la poêle avec un peu d\'huile d\'olive, sans les cuire. Saler et poivrer.',
    'Les ajouter à la sauce avec les olives et cuire environ 20 minutes à feu doux. Rectifier l\'assaisonnement.',
    'Accompagner de spaghetti ou de pommes de terre.',
  ]),
  r('docs-plats-pizza-equilibree', 'Pizza équilibrée faite maison', 'vege', 120, 4, [
    [480, 'g', 'Farine'], [2, 'cs', 'Huile d\'olive'], [12, 'g', 'Levure fraîche'],
    [25, 'cl', 'Eau'], [1, 'pincée', 'Sucre'], [200, 'ml', 'Coulis de tomate'],
    [1, 'pc', 'Oignon'], [10, 'pc', 'Tomate cerise'], [1, 'poignée', 'Épinard'],
    [100, 'g', 'Maïs'], [1, 'pc', 'Courgette'], [1, 'pc', 'Poivron'],
    [2, 'tranche', 'Jambon cuit'], [1, 'pc', 'Mozzarella'], [50, 'g', 'Fromage râpé'],
    [1, 'cc', 'Origan'], [1, 'cc', 'Basilic'], [1, 'cc', 'Thym'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Verser dans un bol l\'eau tiède avec la levure fraîche émiettée et la pincée de sucre, laisser reposer 5 minutes.',
    'Pendant ce temps, verser la farine et le sel dans un saladier et mélanger.',
    'Ajouter le mélange eau-levure et l\'huile d\'olive, mélanger jusqu\'à obtenir une belle boule.',
    'Pétrir 2 à 3 minutes, recouvrir le saladier d\'un drap et laisser gonfler 1 h 30 à 3 h à température ambiante.',
    'Étaler la pâte au rouleau et la garnir : coulis de tomate, légumes à volonté, jambon, mozzarella et fromage râpé.',
    'Assaisonner de sel, poivre, paprika, basilic, origan et thym.',
    'Cuire au four à 220 °C pendant 10 à 20 minutes selon le four.',
  ]),
  r('docs-plats-plumes-chef', 'Plumes du chef', 'viande', 300, 12, [
    [1, 'kg', 'Plumes'], [800, 'g', 'Bœuf haché'], [400, 'g', 'Veau haché'],
    [1, 'pc', 'Aubergine'], [2, 'pc', 'Courgette'], [2, 'pc', 'Oignon rouge'],
    [2, 'pc', 'Oignon'], [4, 'pc', 'Carotte'], [800, 'g', 'Tomate pelée'],
    [1, 'pc', 'Concombre'], [4, 'gousse', 'Ail'], [20, 'cl', 'Vin rouge'],
    [4, 'cs', 'Huile d\'olive'], [1, 'cs', 'Noix de muscade'], [1, 'cs', 'Thym'],
    [1, 'cs', 'Marjolaine'], [1, 'cs', 'Basilic'], [1, 'cs', 'Origan'],
    [1, 'cs', 'Romarin'], [1, 'pc', 'Feuille de laurier'],
    [2, 'pc', 'Cube de bouillon de volaille'], [20, 'cl', 'Crème fraîche'],
    [100, 'g', 'Parmesan'], [150, 'g', 'Mozzarella'], [100, 'g', 'Gruyère'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Faire chauffer 2 cuillères à soupe d\'huile dans une casserole à feu moyen. Ajouter les oignons, l\'ail, le laurier, la noix de muscade et le vin. Laisser cuire jusqu\'à réduction complète du vin.',
    'Ajouter le concombre, l\'aubergine, les courgettes, les carottes et les tomates coupés en dés.',
    'Faire cuire à feu doux pendant 4 heures en remuant de temps en temps.',
    'Faire chauffer le reste d\'huile dans une poêle à feu vif, ajouter les deux viandes, saler, poivrer et cuire à feu moyen.',
    'Mixer la sauce de légumes et y ajouter la viande.',
    'Préchauffer le four à 170 °C.',
    'Remplir les plats en alternant pâtes, sauce, crème fraîche et parmesan, puis pâtes, sauce, crème fraîche et mozzarella, puis pâtes et sauce.',
    'Terminer par une couche du mélange des trois fromages et enfourner.',
  ]),
  r('docs-plats-poisson-pane-avoine', 'Poisson blanc pané aux flocons d\'avoine', 'poisson', 30, 4, [
    [800, 'g', 'Poisson blanc'], [1, 'kg', 'Brocoli'], [2, 'pc', 'Œuf'],
    [2, 'cs', 'Farine'], [3, 'cs', 'Flocons d\'avoine'], [50, 'g', 'Parmesan'],
    [1, 'pc', 'Citron'], [2, 'cs', 'Huile d\'olive'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Découper le poisson blanc en morceaux de taille moyenne et les assaisonner de sel et poivre.',
    'Les tremper dans les œufs battus puis dans la farine mélangée aux flocons d\'avoine.',
    'Les faire cuire à la poêle avec une cuillère à soupe d\'huile d\'olive.',
    'Faire griller les brocolinis à la poêle avec une cuillère à soupe d\'huile d\'olive et les assaisonner de gros sel et poivre.',
    'Servir avec du parmesan râpé sur les brocolinis et du jus de citron frais sur le poisson.',
    'Accompagner d\'un féculent au choix : pommes de terre, quinoa, pâtes, riz ou boulgour.',
  ]),
  r('docs-plats-poivrons-farcis', 'Poivrons farcis au poulet, courgette, semoule et coulis de tomates', 'volaille', 70, 2, [
    [2, 'pc', 'Poivron rouge'], [120, 'g', 'Filet de poulet'],
    [30, 'g', 'Graines de couscous'], [1, 'pc', 'Courgette'],
    [200, 'ml', 'Coulis de tomate'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Chauffer le four à 200 °C.',
    'Laver et couper les poivrons en deux, les épépiner et retirer les membranes blanches.',
    'Laver la courgette, l\'éplucher et la couper en tout petits morceaux.',
    'Découper les filets de poulet en petits morceaux.',
    'Faire cuire la semoule comme indiqué sur l\'emballage, sans ajouter de matière grasse, puis l\'égrainer.',
    'Dans un saladier, préparer la farce en mélangeant la semoule, le poulet, la courgette et la sauce. Saler et poivrer.',
    'Garnir les poivrons de farce, ajouter un peu d\'eau au fond du plat et enfourner environ 50 minutes.',
  ]),
  r('docs-plats-poelee-pdt-bacon', 'Poêlée de pommes de terre, bacon, œufs et petits légumes', 'viande', 35, 2, [
    [4, 'pc', 'Pomme de terre'], [3, 'pc', 'Blanc de poireau'],
    [100, 'g', 'Allumettes de bacon'], [1, 'pc', 'Échalote'], [20, 'cl', 'Crème d\'avoine'],
    [2, 'pc', 'Œuf'], [2, 'cs', 'Parmesan'], [1, 'cc', 'Huile d\'olive'],
    [1, 'botte', 'Ciboulette'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four à 210 °C.',
    'Dans une poêle, faire revenir 5 minutes en remuant l\'échalote ciselée, les pommes de terre coupées en rondelles et les allumettes de bacon dans une cuillère à café d\'huile d\'olive.',
    'Ajouter les rondelles de poireaux lavées et continuer à mélanger quelques minutes à feu vif.',
    'Ajouter la crème et le poivre, mélanger et baisser le feu. Laisser revenir 10 à 15 minutes à couvert.',
    'Casser les deux œufs sur le mélange de poireaux, saupoudrer de parmesan puis enfourner la poêle 5 minutes.',
    'Parsemer de ciboulette avant de servir.',
  ]),
  r('docs-plats-pates-brocoli-oeuf-jambon', 'Pâtes complètes, brocoli, œuf et jambon', 'viande', 25, 2, [
    [120, 'g', 'Pâtes complètes'], [300, 'g', 'Brocoli'], [2, 'pc', 'Œuf'],
    [3, 'tranche', 'Jambon cuit'], [1, 'pc', 'Échalote'], [10, 'cl', 'Crème légère'],
    [1, 'cc', 'Huile d\'olive'], [1, 'cc', 'Paprika'], [1, 'cc', 'Ail en poudre'],
    [1, 'cc', 'Herbes de Provence'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Faire cuire le brocoli dans de l\'eau bouillante salée.',
    'Émincer l\'échalote et la faire revenir dans un peu de matière grasse liquide.',
    'Couper le jambon en cubes et l\'ajouter à l\'échalote, laisser cuire quelques minutes.',
    'Faire cuire les pâtes comme indiqué sur l\'emballage.',
    'Une fois les pâtes cuites, les ajouter au mélange échalote-jambon, avec le brocoli cuit et les œufs. Mélanger et laisser cuire.',
    'Une fois les œufs cuits, ajouter le filet de crème, mélanger et rectifier l\'assaisonnement.',
  ]),
  r('docs-plats-pates-jambon-italien', 'Pâtes jambon italien et parmesan', 'viande', 20, 4, [
    [500, 'g', 'Spaghetti'], [4, 'pc', 'Jaune d\'œuf'], [100, 'g', 'Parmesan'],
    [1, 'cs', 'Crème fraîche épaisse'], [12, 'tranche', 'Jambon cru'],
    [2, 'louche', 'Eau de cuisson des pâtes'], [1, 'pincée', 'Poivre'],
  ], [
    'Cuire les pâtes al dente et, en fin de cuisson, conserver deux louches d\'eau de cuisson.',
    'Dans un bol, disposer les jaunes d\'œufs et les battre à la fourchette.',
    'Ajouter 75 g de parmesan et du poivre, mélanger.',
    'Ajouter la cuillère à soupe de crème et remélanger.',
    'Une fois les pâtes égouttées, ajouter une à deux louches d\'eau de cuisson à la préparation selon la texture souhaitée.',
    'Mélanger et ajouter la préparation aux pâtes. Ne plus remettre en cuisson après cela.',
    'Servir immédiatement avec le jambon cru, du poivre et le reste de parmesan.',
  ]),
  r('docs-plats-pates-sauce-poivrons', 'Pâtes, sauce aux poivrons et carottes, jambon et courgettes', 'viande', 30, 2, [
    [120, 'g', 'Pâtes complètes'], [2, 'pc', 'Carotte'], [1, 'pc', 'Poivron rouge'],
    [1, 'pc', 'Poivron jaune'], [1, 'pc', 'Courgette'], [1, 'pc', 'Échalote'],
    [1, 'cs', 'Fromage frais de chèvre'], [50, 'ml', 'Lait'],
    [0.25, 'pc', 'Cube de bouillon de légumes'], [5, 'tranche', 'Jambon cuit'],
    [1, 'cc', 'Ail en poudre'], [1, 'cc', 'Curcuma'], [1, 'cc', 'Herbes de Provence'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Faire cuire les pâtes dans de l\'eau bouillante salée, al dente.',
    'Couper les carottes et le poivron rouge, et l\'échalote si désiré.',
    'Les faire revenir à la poêle avec un fond d\'eau, ajouter le quart de cube de bouillon et mélanger. Laisser cuire environ 7 minutes à feu moyen-fort, en rajoutant un peu d\'eau si elle s\'évapore.',
    'Une fois les carottes et le poivron cuits, les verser dans un récipient haut avec le lait et le fromage frais, puis mixer. Goûter et assaisonner.',
    'Faire cuire la courgette et le poivron jaune à la poêle, et les assaisonner.',
    'Couper le jambon cuit en cubes.',
    'Assembler dans la casserole : pâtes cuites, légumes cuits, sauce et jambon. Laisser cuire à feu moyen 2 minutes.',
  ]),
  r('docs-plats-pates-tomates-aubergine-burrata', 'Pâtes tomate, aubergine et burrata', 'vege', 30, 4, [
    [500, 'g', 'Pâtes'], [250, 'ml', 'Passata'], [2, 'pc', 'Aubergine'],
    [2, 'pc', 'Échalote'], [2, 'cs', 'Mascarpone'], [1, 'pc', 'Burrata'],
    [3, 'cs', 'Huile d\'olive'], [1, 'cc', 'Herbes de Provence'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Faire chauffer l\'eau des pâtes et les cuire très al dente : elles finiront leur cuisson dans la sauteuse.',
    'Couper l\'aubergine en longs bâtons d\'environ 1 cm, et faire de même avec l\'échalote.',
    'Faire chauffer l\'huile d\'olive, y ajouter l\'échalote et la faire revenir 2 minutes, puis ajouter l\'aubergine en remuant fréquemment.',
    'Au bout de 5 minutes, ajouter la sauce tomate et compter encore 5 minutes pour que tout devienne bien moelleux, en remuant souvent.',
    'Ajouter le mascarpone et bien mélanger.',
    'Goûter et rectifier l\'assaisonnement.',
    'Déposer les pâtes dans la sauteuse, mélanger, laisser 2 à 3 minutes sur le feu, puis ajouter la burrata et les herbes et remélanger hors du feu.',
    'Servir dans des assiettes creuses.',
  ]),
  r('docs-plats-peche-thon-salade', 'Pêche au thon, salade de pâtes aux légumes et salade', 'poisson', 25, 4, [
    [4, 'pc', 'Pêche au jus'], [1, 'boîte', 'Thon au naturel'], [2, 'cs', 'Mayonnaise'],
    [2, 'cs', 'Fromage blanc'], [200, 'g', 'Couscous perlé'], [2, 'pc', 'Œuf'],
    [1, 'pc', 'Poivron'], [1, 'pc', 'Courgette'], [1, 'pc', 'Concombre'],
    [2, 'pc', 'Carotte'], [1, 'pc', 'Salade'], [10, 'pc', 'Tomate cerise'],
    [1, 'cs', 'Vinaigre balsamique'], [1, 'cc', 'Oignon en poudre'],
    [1, 'cc', 'Paprika'], [1, 'cc', 'Curcuma'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préparer la pêche au thon : égoutter le thon et le mélanger avec la mayonnaise et le fromage blanc, saler et poivrer.',
    'Garnir les demi-pêches au jus de cette préparation.',
    'Préparer la salade de pâtes : cuire le couscous perlé et les œufs durs.',
    'Couper les poivrons, la courgette, le concombre et les carottes en petits dés.',
    'Mélanger le tout avec la mayonnaise et le fromage blanc, assaisonner de sel, poivre, oignon en poudre, paprika, curcuma et épices méditerranéennes.',
    'Préparer la salade : salade du jardin et tomates cerises, assaisonnées au vinaigre balsamique.',
    'Dresser les trois préparations dans l\'assiette.',
  ]),
  r('docs-plats-quinoa-mais-haricots', 'Quinoa, maïs et haricots rouges', 'vege', 40, 4, [
    [200, 'g', 'Quinoa'], [1, 'pc', 'Oignon rouge'], [1, 'pc', 'Courgette'],
    [1, 'pc', 'Poivron rouge'], [1, 'pc', 'Poivron orange'], [150, 'g', 'Maïs'],
    [450, 'g', 'Haricot rouge'], [1, 'pc', 'Cube de bouillon de légumes'],
    [50, 'cl', 'Eau'], [1, 'cc', 'Paprika'], [1, 'cc', 'Ail en poudre'],
    [1, 'cc', 'Coriandre'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Couper tous les légumes en petits dés, environ de la taille d\'un grain de maïs.',
    'Les disposer dans une grande poêle et y ajouter le maïs et le quinoa cru.',
    'Diluer le cube de bouillon dans l\'eau et l\'ajouter au mélange légumes-quinoa. Assaisonner.',
    'Mélanger et porter à ébullition, puis réduire à feu moyen. Couvrir et laisser mijoter 20 minutes en mélangeant de temps en temps.',
    'Après 20 minutes, ajouter les haricots rouges préalablement bien rincés, mélanger et laisser cuire encore 5 minutes.',
    'Rectifier l\'assaisonnement. Si désiré, ajouter un peu de fromage frais, de sauce piquante ou de coriandre fraîche.',
  ]),
  r('docs-plats-riz-basmati-saumon', 'Riz basmati au saumon, pois gourmand et lait de coco', 'poisson', 45, 4, [
    [4, 'pc', 'Pavé de saumon'], [250, 'g', 'Riz basmati'], [2, 'pc', 'Oignon'],
    [150, 'g', 'Champignon de Paris'], [100, 'ml', 'Vin blanc'],
    [100, 'g', 'Saumon fumé'], [150, 'g', 'Pois gourmand'], [100, 'ml', 'Lait de coco'],
    [1, 'pc', 'Cube de bouillon de légumes'], [1, 'cs', 'Huile d\'olive'],
    [1, 'botte', 'Aneth'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Faire cuire les pavés de saumon au four avec environ 100 ml de bouillon de légumes.',
    'Pendant ce temps, faire revenir à la poêle les oignons et les champignons avec une cuillère à soupe de matière grasse, laisser cuire 3 à 4 minutes.',
    'Ajouter le vin blanc et laisser cuire environ 1 minute.',
    'Ajouter le riz, mélanger et laisser cuire 5 minutes.',
    'Faire chauffer 1 litre d\'eau bouillante avec le cube de bouillon, puis l\'ajouter et laisser cuire 15 minutes à feu doux.',
    'Ajouter les pois gourmands et le lait de coco, laisser cuire environ 10 minutes jusqu\'à ce que le riz et les légumes soient cuits. Saler et poivrer.',
    'Au dernier moment, ajouter le saumon fumé coupé en lamelles.',
    'Dresser le risotto dans l\'assiette, ajouter le pavé de saumon frais par-dessus et saupoudrer d\'aneth.',
  ]),
  r('docs-plats-salade-ete', 'Salade d\'été', 'vege', 15, 5, [
    [25, 'pc', 'Tomate cerise'], [3, 'pc', 'Orange'], [10, 'pc', 'Olive noire'],
    [12, 'pc', 'Tomate séchée'], [1, 'pc', 'Roquette'], [4, 'cs', 'Huile d\'olive'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Couper les tomates cerises, les oranges, les olives et les tomates séchées en petits dés.',
    'Ajouter la roquette ciselée et l\'huile d\'olive, puis saler, poivrer et mélanger le tout.',
    'Disposer la salade dans une assiette et déguster, éventuellement avec des samossas.',
  ]),
  r('docs-plats-samossas-courgette-chevre', 'Samossas courgette et chèvre', 'vege', 25, 5, [
    [1, 'paquet', 'Feuille de brick'], [2, 'pc', 'Courgette'], [2, 'pc', 'Oignon'],
    [2, 'gousse', 'Ail'], [1, 'pc', 'Chèvre frais'], [1, 'cc', 'Massalé'],
    [1, 'pincée', 'Piment en poudre'], [3, 'cs', 'Huile d\'olive'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Émincer les oignons et les faire revenir dans un gros filet d\'huile d\'olive à feu moyen, dans une sauteuse, pendant 2 à 3 minutes.',
    'Ajouter l\'ail émincé finement et poursuivre la cuisson 1 à 2 minutes.',
    'Ajouter les courgettes coupées en petits dés, le sel et les épices, puis prolonger la cuisson 3 à 4 minutes. Les courgettes doivent être à la fois croquantes et fondantes.',
    'Sortir la préparation du feu et façonner les samossas en farcissant une demi-feuille de brick avec une cuillère à soupe de préparation et un morceau de chèvre.',
    'Faire cuire les samossas avec un peu d\'huile d\'olive 1 minute 30 de chaque côté, et réserver au chaud.',
  ]),
  r('docs-plats-sauce-tomates-haricots', 'Sauce tomate aux haricots rouges', 'vege', 20, 2, [
    [2, 'pc', 'Oignon'], [2, 'pc', 'Carotte'], [200, 'g', 'Tomate pelée'],
    [200, 'g', 'Haricot rouge'], [1, 'cs', 'Fromage frais'], [1, 'cc', 'Paprika'],
    [1, 'cc', 'Origan'], [1, 'cc', 'Ail en poudre'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Faire revenir à la poêle l\'oignon coupé en fines lamelles et les carottes coupées en fines rondelles.',
    'Après 10 minutes, ajouter les tomates pelées et laisser cuire quelques minutes.',
    'Pendant ce temps, égoutter les haricots rouges, puis les ajouter au mélange.',
    'Ajouter le fromage frais, mélanger et assaisonner selon vos goûts.',
    'Laisser cuire encore 2 à 3 minutes.',
    'Cette sauce s\'utilise avec du riz et des lentilles, dans un wrap ou dans un croque-monsieur.',
  ]),
  r('docs-plats-soupe-nouilles-epicee', 'Soupe de nouilles légèrement épicée', 'vege', 30, 3, [
    [140, 'g', 'Nouilles de riz'], [1, 'gousse', 'Ail'], [1, 'pc', 'Oignon'],
    [1, 'cs', 'Gingembre en poudre'], [1, 'cs', 'Pâte de curry rouge'],
    [600, 'ml', 'Lait de coco'], [3, 'pc', 'Carotte'], [1, 'pc', 'Poivron rouge'],
    [1, 'pc', 'Brocoli'], [1, 'pc', 'Cube de bouillon'], [1, 'pc', 'Citron vert'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Hacher l\'oignon et l\'ail, les ajouter dans une poêle avec un fond d\'eau.',
    'Ajouter le gingembre et laisser fondre, puis ajouter la pâte de curry et le lait de coco. Laisser réduire.',
    'Ajouter le bouillon et le jus de citron vert.',
    'Découper les carottes en dés et le poivron en fines lanières, les ajouter dans la poêle avec le brocoli, et laisser mijoter environ 15 minutes.',
    'Cuire les nouilles à part selon les instructions du paquet.',
    'Servir la soupe avec les nouilles par-dessus.',
  ]),
  r('docs-plats-tarte-oignons-poivrons-feta', 'Tarte oignons, poivrons, feta et pois chiches', 'vege', 45, 4, [
    [160, 'g', 'Farine'], [60, 'g', 'Fromage blanc'], [4, 'cs', 'Huile d\'olive'],
    [3, 'pc', 'Oignon'], [3, 'pc', 'Poivron'], [150, 'g', 'Feta'],
    [200, 'g', 'Pois chiche'], [2, 'cs', 'Moutarde'], [1, 'cc', 'Curcuma'],
    [1, 'cc', 'Herbes de Provence'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four à 180 °C.',
    'Émincer les oignons et couper les poivrons en fines lamelles, les faire revenir à la poêle avec un peu d\'huile d\'olive jusqu\'à ce qu\'ils soient bien cuits. Épicer.',
    'Préparer la pâte : mélanger la farine, le fromage blanc, 2 cuillères à soupe d\'huile d\'olive, le sel et les épices. Former une boule et l\'étaler.',
    'Disposer un peu de moutarde sur la pâte, puis ajouter la poêlée d\'oignons et de poivrons.',
    'Rincer abondamment les pois chiches et les disposer sur la tarte.',
    'Émietter la feta par-dessus.',
    'Enfourner à 180 °C pendant environ 30 minutes.',
  ]),
  r('docs-plats-tarte-salee-epinards-poivron-lieu', 'Tarte salée épinards, poivron et lieu jaune', 'poisson', 45, 4, [
    [160, 'g', 'Farine'], [60, 'g', 'Fromage blanc'], [4, 'cs', 'Huile d\'olive'],
    [2, 'cc', 'Concentré de tomate'], [2, 'cc', 'Fromage frais'], [2, 'pc', 'Échalote'],
    [1, 'pc', 'Poivron'], [0.5, 'pc', 'Courgette'], [200, 'g', 'Épinard'],
    [150, 'g', 'Lieu jaune'], [1, 'pc', 'Mozzarella'], [1, 'cc', 'Herbes de Provence'],
    [1, 'cc', 'Aneth'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Couper les légumes (poivron, échalotes et courgette) et les faire revenir à la poêle 6 à 8 minutes. Après 5 minutes, ajouter les épinards. Saler et poivrer.',
    'Préparer la pâte : mélanger la farine, le fromage blanc, 2 cuillères à soupe d\'huile d\'olive, le sel et les épices. Former une boule et l\'étaler dans un moule à tarte.',
    'Mélanger le concentré de tomate avec le fromage frais, saler, poivrer et ajouter des herbes de Provence. Étaler ce mélange sur la pâte.',
    'Ajouter les légumes cuits et le poisson coupé en morceaux, préalablement épicé avec un peu d\'aneth et de poivre.',
    'Découper la mozzarella en petites rondelles et les disposer sur la tarte.',
    'Enfourner environ 30 minutes à 180 °C.',
  ]),
  r('docs-plats-tartiflette', 'Tartiflette plus ou moins légère', 'viande', 60, 4, [
    [1, 'kg', 'Pomme de terre'], [2, 'pc', 'Oignon'], [200, 'g', 'Allumettes de bacon'],
    [250, 'ml', 'Crème légère'], [240, 'g', 'Fromage à raclette'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Faire cuire les pommes de terre à l\'eau.',
    'Pendant ce temps, faire rissoler les oignons préalablement émincés et faire revenir les allumettes de bacon.',
    'Une fois les pommes de terre cuites, les couper en morceaux et les disposer dans un grand plat allant au four. Les épicer.',
    'Ajouter les lardons, les oignons et la crème, puis mélanger le tout.',
    'Disposer les tranches de fromage par-dessus.',
    'Enfourner 30 à 40 minutes à 200 °C.',
  ]),
  r('docs-plats-tomate-crevettes', 'Tomate crevettes, salade de pâtes froides et salade', 'poisson', 30, 4, [
    [4, 'pc', 'Tomate cœur de bœuf'], [300, 'g', 'Crevette grise'],
    [2, 'cs', 'Mayonnaise'], [2, 'cs', 'Fromage blanc'], [250, 'g', 'Farfalle'],
    [10, 'pc', 'Tomate cerise'], [8, 'pc', 'Tomate séchée'],
    [4, 'tranche', 'Jambon de Parme'], [50, 'g', 'Parmesan'], [1, 'pc', 'Roquette'],
    [1, 'cc', 'Huile de truffe'], [3, 'cs', 'Huile d\'olive'],
    [1, 'pc', 'Salade'], [1, 'cs', 'Vinaigre balsamique'],
    [1, 'cs', 'Graines de lin'], [1, 'cs', 'Graines de courge'],
    [1, 'cs', 'Graines de sésame'], [1, 'botte', 'Ciboulette'], [1, 'botte', 'Persil'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préparer la tomate crevettes : évider les tomates cœur de bœuf, mélanger les crevettes avec la mayonnaise et le fromage blanc, saler et poivrer, puis en garnir les tomates.',
    'Préparer la salade de pâtes froides : cuire les farfalles et les laisser refroidir.',
    'Y ajouter les tomates cerises, les tomates demi-séchées, le jambon de Parme, les copeaux de parmesan et la roquette.',
    'Assaisonner de quelques gouttes d\'huile de truffe et de 2 à 3 cuillères à soupe de l\'huile des tomates demi-séchées, saler et poivrer.',
    'Préparer la salade : salade du jardin, tomates cerises, vinaigre balsamique, graines de lin, de courge et de sésame, ciboulette et persil du jardin.',
    'Dresser les trois préparations dans l\'assiette.',
  ]),
  r('docs-plats-tortiglioni-champignons', 'Tortiglioni, sauce légère aux champignons', 'vege', 30, 4, [
    [500, 'g', 'Tortiglioni'], [500, 'g', 'Champignon de Paris'], [1, 'pc', 'Oignon'],
    [3, 'gousse', 'Ail'], [250, 'ml', 'Bouillon de volaille'], [1, 'pc', 'Mozzarella'],
    [1, 'cs', 'Mascarpone'], [3, 'cs', 'Maïzena'], [20, 'g', 'Beurre'],
    [100, 'ml', 'Crème légère'], [1, 'cc', 'Paprika'], [1, 'botte', 'Ciboulette'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Émincer l\'oignon et les champignons.',
    'Faire chauffer le bouillon ; une fois qu\'il bout, ajouter la Maïzena et bien mélanger de façon à obtenir une texture légèrement épaisse. Réserver.',
    'Faire revenir l\'ail et l\'oignon dans un peu de beurre ou d\'huile, puis ajouter les champignons.',
    'Pendant ce temps, faire cuire les pâtes très al dente, 2 minutes de moins que le temps recommandé.',
    'Chauffer le bouillon épaissi à feu doux et ajouter la crème et le mascarpone, mélanger et rectifier l\'assaisonnement.',
    'Détailler la mozzarella en petits morceaux, l\'insérer dans la sauce, mélanger à nouveau et ajouter aux pâtes.',
    'Remettre le mélange sur le feu 1 à 2 minutes en mélangeant bien.',
    'Servir en parsemant de ciboulette hachée.',
  ]),
  // ========================== DESSERTS ==========================
  r('docs-desserts-cantuchini', 'Cantuccini', 'dessert', 60, 8, [
    [140, 'g', 'Sucre'], [2, 'sachet', 'Sucre vanillé'], [50, 'g', 'Huile de pépins de raisin'],
    [300, 'g', 'Farine'], [1, 'sachet', 'Levure chimique'], [1, 'pc', 'Orange'],
    [200, 'g', 'Amande'], [2, 'pc', 'Œuf'], [1, 'pincée', 'Sel'],
  ], [
    'Préchauffer le four à 180 °C.',
    'Faire blanchir les œufs avec le sucre en poudre, le sucre vanillé, une belle pincée de sel et les zestes de l\'orange.',
    'Ajouter l\'huile très progressivement, tout en continuant de fouetter.',
    'Ajouter les amandes, mélanger à la main ou à la cuillère, puis la farine tamisée avec la levure. Mélanger pour obtenir une pâte homogène, sans insister.',
    'Façonner trois boudins de 40 cm de long et les déposer sur une plaque en métal recouverte de papier sulfurisé. Enfourner 25 minutes.',
    'Déposer les boudins sur une planche à découper et couper des tronçons en biseau d\'1 cm de large maximum, avec un couteau qui coupe bien.',
    'Déposer les cantuccini à plat sur la plaque et remettre à cuire environ 10 minutes, selon le degré de coloration souhaité.',
    'Les laisser refroidir sur une grille, puis les stocker dans une boîte hermétique : ils se gardent 3 semaines et sont meilleurs 24 heures après.',
  ]),
  r('docs-desserts-clafoutis-framboises-myrtilles', 'Clafoutis aux framboises et myrtilles', 'dessert', 50, 6, [
    [300, 'g', 'Framboise'], [200, 'g', 'Myrtille'], [170, 'ml', 'Lait'],
    [20, 'g', 'Sucre'], [2, 'pc', 'Œuf'], [60, 'g', 'Farine'], [1, 'pincée', 'Sel'],
  ], [
    'Remplir le plat de framboises et de myrtilles.',
    'Dans un saladier, mélanger les œufs avec le sucre, puis ajouter la farine, le lait et la pincée de sel.',
    'Verser cette préparation sur les fruits et enfourner 40 minutes à 210 °C.',
    'Pour un clafoutis un peu humide au milieu, 40 minutes suffisent ; pour un résultat plus compact, compter 45 à 50 minutes.',
  ]),
  r('docs-desserts-flans-legumes', 'Flans aux légumes', 'vege', 45, 8, [
    [300, 'g', 'Farine d\'épeautre'], [400, 'g', 'Légumes variés'],
    [200, 'ml', 'Crème légère'], [4, 'pc', 'Œuf'], [1, 'cc', 'Noix de muscade'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four à 200 °C.',
    'Laver, éplucher et découper finement les légumes choisis : oignon, carotte, poivron rouge et brocoli.',
    'Dans un saladier, mélanger tous les ingrédients.',
    'Cuire pendant 30 minutes.',
    'Servir froid, chaud ou tiède, avec une salade garnie.',
  ]),
  r('docs-desserts-gateau-choco-laurie', 'Gâteau au chocolat de Laurie', 'dessert', 30, 6, [
    [50, 'g', 'Farine'], [3, 'pc', 'Œuf'], [100, 'g', 'Sucre'],
    [200, 'g', 'Chocolat noir'], [100, 'g', 'Beurre'],
  ], [
    'Faire fondre le chocolat avec le beurre.',
    'À part, mélanger les œufs avec le sucre et la farine, puis y ajouter le mélange chocolat-beurre.',
    'Cuire 20 minutes au four à 180 °C.',
  ]),
  r('docs-desserts-gateau-choco-domi', 'Gâteau au chocolat', 'dessert', 50, 4, [
    [200, 'g', 'Chocolat noir'], [150, 'g', 'Beurre'], [3, 'pc', 'Œuf'],
    [125, 'g', 'Sucre'], [100, 'g', 'Poudre d\'amandes'], [50, 'g', 'Purée de noisettes'],
    [50, 'g', 'Noix'], [2, 'cs', 'Raisin de Corinthe'],
  ], [
    'Préchauffer le four à 180 °C. Tapisser de papier sulfurisé le fond et les parois d\'un moule carré de 20 x 20 cm.',
    'Casser le chocolat en morceaux et le faire fondre avec le beurre, au bain-marie ou au micro-ondes.',
    'Concasser grossièrement les noix.',
    'Battre les œufs avec le sucre dans un saladier, puis incorporer sans cesser de fouetter le mélange chocolat-beurre.',
    'Terminer par la poudre d\'amandes.',
    'Verser la préparation dans le moule, parsemer de noix et faire cuire 35 minutes au four.',
    'Laisser refroidir sur une grille, découper en portions carrées et servir.',
  ]),
  r('docs-desserts-gateau-flocons-avoine', 'Gâteau aux flocons d\'avoine, pomme, poire et cannelle', 'dessert', 45, 6, [
    [150, 'g', 'Flocons d\'avoine'], [30, 'cl', 'Lait'], [1, 'pc', 'Œuf'],
    [30, 'g', 'Poudre d\'amandes'], [1, 'cc', 'Miel'], [2, 'cc', 'Cannelle'],
    [2, 'pc', 'Pomme'], [1, 'pc', 'Poire'], [1, 'pincée', 'Sel'],
  ], [
    'Couper les pommes et la poire en dés.',
    'Dans un saladier, mélanger tous les ingrédients et y ajouter les dés de fruits.',
    'Verser dans un moule beurré et enfourner 35 minutes à 200 °C.',
    'Démouler une fois le cake bien refroidi.',
  ]),
  r('docs-desserts-pudding-vanille', 'Pudding à la vanille', 'dessert', 15, 6, [
    [50, 'g', 'Pudding en poudre'], [750, 'ml', 'Lait'], [30, 'g', 'Sucre'],
  ], [
    'Dans une grande tasse, verser le sachet de pudding en poudre et y ajouter environ 100 ml de lait tout en mélangeant, jusqu\'à disparition des grumeaux. Réserver.',
    'Verser le reste du lait (650 ml) dans une casserole, ajouter le sucre et porter à ébullition.',
    'Une fois le lait en ébullition, le sortir du feu et ajouter le mélange pudding-lait sans cesser de mélanger.',
    'Remettre à cuire 1 minute tout en mélangeant.',
    'Verser dans des petits raviers et laisser refroidir.',
  ]),
  r('docs-desserts-riz-au-lait', 'Riz au lait', 'dessert', 40, 8, [
    [125, 'g', 'Riz rond'], [1, 'l', 'Lait'], [25, 'g', 'Sucre'],
    [1, 'pc', 'Gousse de vanille'], [1, 'pincée', 'Sel'],
  ], [
    'Porter le litre de lait à ébullition avec la gousse de vanille et la pincée de sel.',
    'Une fois l\'ébullition atteinte, ajouter le riz.',
    'Baisser le feu et laisser cuire à feu doux environ 30 à 35 minutes, en mélangeant toutes les 5 minutes.',
    'Une fois le riz au lait cuit, ajouter le sucre et retirer la gousse de vanille.',
    'Verser dans des petits bols et laisser refroidir, ou déguster tiède.',
  ]),
  r('docs-desserts-torta-paradiso', 'Torta Paradiso', 'dessert', 55, 8, [
    [4, 'pc', 'Œuf'], [180, 'g', 'Sucre'], [1, 'sachet', 'Levure chimique'],
    [120, 'g', 'Beurre'], [100, 'g', 'Fécule de pomme de terre'], [180, 'g', 'Farine'],
    [1, 'pc', 'Citron'], [2, 'cs', 'Sucre glace'],
  ], [
    'Mélanger les œufs avec le sucre, puis ajouter le zeste de citron râpé.',
    'Ajouter le beurre fondu et bien mélanger.',
    'Ajouter la fécule de pomme de terre et la farine.',
    'Ajouter la levure en dernier.',
    'Cuire à 180 °C pendant 40 minutes.',
    'Laisser refroidir avant de saupoudrer de sucre glace.',
  ]),

  // ============================ APÉRO ============================
  r('docs-apero-boulettes-flocons-courgette', 'Boulettes apéritives aux flocons d\'avoine et à la courgette', 'apero', 35, 4, [
    [0.5, 'pc', 'Courgette'], [1, 'pc', 'Oignon'], [50, 'g', 'Flocons d\'avoine'],
    [15, 'g', 'Parmesan'], [1, 'pc', 'Œuf'], [1, 'cc', 'Curry'],
    [1, 'cc', 'Paprika'], [1, 'botte', 'Basilic'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four à 180 °C.',
    'Peler et émincer finement l\'oignon, le faire revenir dans une poêle légèrement huilée avec le curry jusqu\'à ce qu\'il soit translucide.',
    'Pendant ce temps, râper la courgette.',
    'Dans un saladier, mélanger la courgette râpée, l\'oignon émincé, les flocons d\'avoine, le fromage râpé, le basilic finement ciselé, le paprika, le sel et le poivre.',
    'Une fois la préparation homogène, ajouter l\'œuf préalablement battu en omelette et bien mélanger.',
    'Former des boulettes avec les mains légèrement humides, puis les disposer sur une plaque recouverte de papier cuisson.',
    'Enfourner 20 à 25 minutes selon les fours : les boulettes doivent être dorées.',
  ]),
  r('docs-apero-pois-chiches-grilles', 'Pois chiches grillés pour l\'apéro', 'apero', 55, 4, [
    [340, 'g', 'Pois chiche'], [1, 'cc', 'Huile d\'olive'], [1, 'cc', 'Paprika'],
    [1, 'cc', 'Curry'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four à 180 °C.',
    'Rincer les pois chiches sous l\'eau froide, les égoutter et les éponger avec de l\'essuie-tout.',
    'Mélanger les pois chiches avec l\'huile et les épices.',
    'Les répartir sur une plaque de cuisson recouverte de papier sulfurisé.',
    'Faire griller au four pendant 40 à 50 minutes.',
  ]),
  r('docs-apero-roules-courgettes-saumon', 'Roulés apéritifs de courgettes au saumon fumé', 'apero', 25, 4, [
    [2, 'pc', 'Courgette'], [6, 'tranche', 'Saumon fumé'],
    [200, 'g', 'Fromage frais'], [2, 'cs', 'Huile d\'olive'],
    [1, 'botte', 'Aneth'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Préchauffer le four en position gril.',
    'Laver les courgettes et couper les extrémités. À l\'aide d\'une mandoline ou d\'un économe, tailler les courgettes en tranches fines dans le sens de la longueur.',
    'Recouvrir la plaque du four de papier sulfurisé, déposer les tranches de courgettes et les badigeonner d\'une cuillère à soupe d\'huile d\'olive au pinceau.',
    'Saler, poivrer et enfourner 10 minutes. À mi-cuisson, retourner les tranches et badigeonner l\'autre face avec le reste d\'huile.',
    'Retirer les tranches grillées du four et les laisser refroidir complètement.',
    'Dans un saladier, assaisonner le fromage frais avec l\'aneth, le sel et le poivre.',
    'Étaler une cuillère à soupe de fromage frais sur chaque tranche froide, ajouter le saumon fumé et rouler.',
  ]),
  r('docs-apero-toasts-crevettes', 'Toasts de seigle aux crevettes et tomates séchées', 'apero', 10, 8, [
    [200, 'g', 'Fromage frais'], [200, 'g', 'Crevette grise'],
    [8, 'pc', 'Tomate séchée'], [8, 'tranche', 'Pain de seigle'],
    [1, 'botte', 'Ciboulette'], [1, 'pincée', 'Piment d\'Espelette'], [1, 'pincée', 'Poivre'],
  ], [
    'Émincer finement les tomates séchées et les mélanger avec le fromage frais.',
    'Ajouter la ciboulette et poivrer.',
    'Toaster les tranches de pain au grille-pain, puis les couper en bouchées.',
    'Répartir le mélange au fromage frais sur les morceaux de pain et déposer une crevette sur chacun.',
    'Planter une pique apéritive en bois dans chaque toast pour maintenir les ingrédients.',
    'Saupoudrer chaque toast d\'une pincée de piment d\'Espelette.',
  ]),

  // ============================ EN-CAS ============================
  r('docs-encas-biscuits-fromage-blanc', 'Petits biscuits au fromage blanc, yaourt et pépites de chocolat', 'encas', 35, 15, [
    [100, 'g', 'Flocons d\'avoine'], [150, 'g', 'Farine'], [50, 'g', 'Farine de lupin'],
    [50, 'g', 'Fromage blanc'], [100, 'g', 'Yaourt nature'], [80, 'g', 'Compote de pommes'],
    [15, 'g', 'Beurre'], [1, 'pc', 'Œuf'], [80, 'g', 'Pépites de chocolat noir'],
    [1, 'pincée', 'Sel'],
  ], [
    'Préchauffer le four à 170 °C.',
    'Dans un grand récipient, verser les flocons d\'avoine, la farine grise, la farine de lupin, les pépites de chocolat noir et le sel. Mélanger le tout.',
    'Faire fondre le beurre au micro-ondes quelques secondes.',
    'Ajouter au mélange sec la compote de pommes, le fromage blanc, le yaourt, l\'œuf et le beurre fondu. Mélanger.',
    'Former de petites boules avec la pâte et les aplatir pour former de petits biscuits.',
    'Les disposer sur une plaque recouverte de papier sulfurisé et enfourner environ 15 minutes.',
    'Ces biscuits se conservent 2 à 3 jours à température ambiante, 4 à 5 jours au réfrigérateur.',
  ]),
  r('docs-encas-granola-noisettes-choco', 'Granola aux noisettes et au chocolat noir', 'encas', 50, 12, [
    [700, 'g', 'Flocons d\'avoine'], [350, 'g', 'Compote de pommes'],
    [2, 'cs', 'Huile d\'olive'], [50, 'ml', 'Eau'], [200, 'g', 'Noisette'],
    [175, 'g', 'Chocolat noir'], [75, 'g', 'Graines de courge'],
    [1, 'cc', 'Cannelle'], [1, 'pincée', 'Sel'],
  ], [
    'Disposer dans un grand récipient les flocons d\'avoine, le sel et la cannelle, puis mélanger.',
    'Concasser les noisettes et les ajouter aux flocons d\'avoine. Mélanger.',
    'Ajouter la compote de pommes, l\'huile d\'olive et l\'eau. Mélanger le tout.',
    'Étaler le granola sur une plaque recouverte de papier sulfurisé et enfourner environ 40 minutes à 140 °C, en mélangeant toutes les 10 à 15 minutes.',
    'Pendant ce temps, concasser le chocolat noir.',
    'Une fois la cuisson terminée, laisser refroidir le mélange sur la plaque, puis ajouter le chocolat concassé et les graines de courge. Mélanger.',
    'Ce granola se conserve dans un bocal hermétique environ 10 jours.',
  ]),
  r('docs-encas-minis-cakes-sales', 'Minis cakes salés courgette, carottes et filet de Saxe', 'encas', 45, 12, [
    [160, 'g', 'Farine complète'], [2, 'pc', 'Œuf'], [100, 'ml', 'Lait'],
    [1, 'cs', 'Huile d\'olive'], [0.5, 'sachet', 'Levure chimique'],
    [30, 'g', 'Gruyère'], [0.5, 'pc', 'Courgette'], [5, 'pc', 'Carotte'],
    [6, 'tranche', 'Filet de Saxe'], [6, 'pc', 'Tomate séchée'],
    [1, 'cc', 'Curcuma'], [1, 'cc', 'Paprika'], [1, 'cc', 'Basilic'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Dans un récipient, mélanger la farine avec la levure chimique, puis ajouter les œufs, le lait et l\'huile d\'olive et mélanger le tout.',
    'Râper la courgette et les carottes, les ajouter à la pâte. Ajouter également le fromage râpé et les tranches de filet de Saxe coupées en petits morceaux, puis mélanger.',
    'Si désiré, ajouter les tomates séchées coupées et des morceaux de fromage de chèvre.',
    'Assaisonner et disposer la pâte dans des petits moules en silicone.',
    'Faire cuire au four à 180 °C pendant 30 minutes. Pour un grand cake salé, compter au minimum 50 minutes.',
  ]),
  r('docs-encas-muffins-choco-courgette', 'Muffins chocolat noir et courgette', 'encas', 30, 10, [
    [120, 'g', 'Chocolat noir'], [150, 'g', 'Courgette'], [30, 'g', 'Sucre de coco'],
    [50, 'g', 'Farine'], [2, 'pc', 'Œuf'], [1, 'cc', 'Levure chimique'],
    [1, 'pincée', 'Sel'],
  ], [
    'Préchauffer le four à 170 °C et faire fondre le chocolat noir au bain-marie.',
    'Dans un récipient, battre les œufs avec le sucre.',
    'Peler et râper finement la courgette crue, puis l\'ajouter au mélange œufs-sucre.',
    'Ajouter le chocolat fondu et mélanger le tout.',
    'Dans un bol, mélanger la farine, la levure chimique et le sel, puis ajouter ce mélange à la pâte jusqu\'à obtenir une préparation homogène.',
    'Huiler et fariner les moules à muffins, verser la préparation et enfourner 18 à 20 minutes à 170 °C.',
    'Laisser refroidir puis démouler.',
  ]),

  // ========================= PETITS DÉJ =========================
  r('docs-petitdej-pancakes-yaourt', 'Pancakes au yaourt', 'petitdej', 20, 2, [
    [2, 'pc', 'Œuf'], [80, 'g', 'Flocons d\'avoine'], [30, 'g', 'Farine d\'épeautre'],
    [30, 'g', 'Farine complète'], [1, 'pc', 'Yaourt nature'],
    [1, 'cc', 'Huile d\'olive'], [1, 'pincée', 'Sel'],
  ], [
    'Mélanger les 2 jaunes d\'œufs avec le yaourt.',
    'Ajouter les flocons d\'avoine et la farine.',
    'Monter les blancs d\'œufs en neige avec la pincée de sel, puis les ajouter à la préparation.',
    'Mettre une poêle à chauffer avec une cuillère à café de matière grasse liquide et verser une louche de pâte pour former les pancakes.',
    'Laisser cuire 1 à 2 minutes de chaque côté pour qu\'ils soient dorés.',
    'Garnir de fruits, de fruits oléagineux ou d\'une cuillère à café de garniture sucrée : miel, confiture, sirop d\'érable.',
  ]),
  r('docs-petitdej-pancakes-banane', 'Pancakes à la banane', 'petitdej', 20, 2, [
    [2, 'pc', 'Banane'], [2, 'pc', 'Œuf'], [80, 'g', 'Flocons d\'avoine'],
    [60, 'ml', 'Lait'], [1, 'pincée', 'Levure chimique'], [1, 'pincée', 'Sel'],
  ], [
    'Dans un saladier, écraser les bananes à l\'aide d\'une fourchette. Ajouter les œufs et mélanger.',
    'Mixer les flocons d\'avoine pour obtenir une texture lisse, puis les ajouter à la préparation avec la levure chimique, le sel et le lait. Mélanger à nouveau.',
    'Dans une poêle, verser de la pâte et l\'étaler avec le dos de la cuillère.',
    'Une fois que de petits trous se forment dans la pâte, retourner les pancakes.',
    'Laisser cuire encore quelques secondes et répéter l\'opération jusqu\'à épuisement de la pâte.',
    'Garnir de fruits frais, fruits secs, beurre d\'oléagineux, chocolat noir fondu ou sirop d\'érable.',
  ]),
  r('docs-petitdej-pancakes-compote', 'Pancakes à la compote de pommes', 'petitdej', 15, 4, [
    [100, 'g', 'Compote de pommes'], [100, 'g', 'Farine complète'],
    [250, 'ml', 'Lait'], [0.5, 'sachet', 'Levure chimique'], [1, 'pincée', 'Sel'],
  ], [
    'Mélanger tous les ingrédients ensemble.',
    'La pâte est prête : faire chauffer les pancakes 1 minute de chaque côté.',
    'Garnir et déguster.',
  ]),
  r('docs-petitdej-pancakes-patate-douce', 'Pancakes à la patate douce', 'petitdej', 20, 1, [
    [100, 'g', 'Patate douce'], [1, 'pc', 'Œuf'], [1, 'pc', 'Blanc d\'œuf'],
    [15, 'g', 'Farine complète'], [50, 'ml', 'Boisson végétale'],
    [1, 'cs', 'Compote de pommes'], [1, 'pincée', 'Sel'],
  ], [
    'Couper la patate douce en petits cubes. Dans un plat allant au micro-ondes, disposer un peu d\'eau et les cubes, puis cuire 3 à 4 minutes au micro-ondes.',
    'Une fois cuite, jeter le reste d\'eau, verser la patate douce dans un récipient et l\'écraser à la fourchette.',
    'Une fois réduite en purée, ajouter le reste des ingrédients et mélanger le tout.',
    'Dans une poêle huilée, former des petits cercles avec la pâte et faire cuire environ une minute de chaque côté, à feu modéré pour ne pas les brûler.',
  ]),

  // ===================== NOUVELLES RECETTES =====================
  r('docs-plats-soupe-carottes-poivrons', 'Soupe inratable carottes et poivrons', 'vege', 45, 4, [
    [1, 'kg', 'Carotte'], [2, 'pc', 'Poivron rouge'], [3, 'pc', 'Oignon'],
    [1, 'l', 'Bouillon de volaille'], [2, 'cs', 'Huile d\'olive'],
    [10, 'cl', 'Crème épaisse'], [2, 'cs', 'Graines de courge'],
    [1, 'pincée', 'Piment d\'Espelette'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Faire revenir l\'oignon grossièrement coupé dans une casserole avec un peu d\'huile d\'olive.',
    'Ajouter les carottes épluchées et le poivron émincé.',
    'Faire revenir le plus longtemps possible, puis mouiller de bouillon de volaille jusqu\'à recouvrir les légumes.',
    'Laisser mijoter : le plus longtemps sera le mieux.',
    'Mixer le tout et passer le liquide dans une passoire fine.',
    'Rectifier l\'assaisonnement.',
    'Monter la crème fraîche et l\'assaisonner de gros sel, piment d\'Espelette et poivre.',
    'Faire revenir les graines de courge à la poêle.',
    'Servir dans des bols avec un peu de crème et des graines de courge.',
  ]),
  r('docs-plats-creme-butternut-coco', 'Crème de butternut et nuage de lait de coco', 'vege', 45, 4, [
    [1, 'pc', 'Butternut'], [2, 'pc', 'Oignon'], [200, 'ml', 'Lait de coco'],
    [10, 'cl', 'Crème fraîche'], [1, 'l', 'Bouillon de volaille'],
    [2, 'cs', 'Huile d\'olive'], [1, 'cc', 'Paprika fumé'],
    [1, 'cs', 'Graines de pavot'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Faire revenir dans une grande casserole l\'oignon avec un peu d\'huile d\'olive.',
    'Éplucher et couper le butternut en petits morceaux, l\'ajouter à l\'oignon.',
    'Faire colorer et attendrir les légumes.',
    'Mouiller de bouillon de façon à recouvrir légèrement les légumes.',
    'Laisser mijoter 20 à 40 minutes selon le temps disponible.',
    'Ajouter 5 à 10 cl de lait de coco selon le goût et mixer le tout.',
    'Rectifier l\'assaisonnement avec du paprika fumé, sel et poivre.',
    'Fouetter la crème fraîche en chantilly, ajouter 5 cl de lait de coco et fouetter à nouveau.',
    'Servir dans un grand bol, ajouter une noquette de crème de lait de coco par-dessus et parsemer de graines de pavot.',
  ]),
  r('docs-plats-veloute-potimarron-chataignes', 'Velouté de potimarron et châtaignes caramélisées', 'vege', 80, 4, [
    [1.5, 'kg', 'Potimarron'], [2, 'l', 'Bouillon de légumes'], [150, 'ml', 'Crème fraîche'],
    [1, 'pc', 'Oignon'], [2, 'gousse', 'Ail'], [200, 'g', 'Châtaigne'],
    [50, 'g', 'Beurre'], [2, 'cc', 'Miel'], [2, 'cc', 'Cumin'],
    [2, 'cs', 'Huile de noix'], [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Tailler l\'écorce des châtaignes en croix à l\'aide d\'un couteau pointu, puis les placer dans un bol au micro-ondes pendant une minute.',
    'Décortiquer les châtaignes cuites et les couper en gros morceaux.',
    'Faire fondre 50 g de beurre, ajouter les châtaignes et les caraméliser avec deux cuillères à café de miel.',
    'Enlever la queue du potimarron et le couper en gros cubes.',
    'Dans une casserole, faire revenir l\'ail et l\'oignon dans l\'huile. Une fois bien dorés, ajouter les cubes de potimarron et les épices, et poursuivre la cuisson à feu moyen une dizaine de minutes.',
    'Ajouter la crème et 1 litre de bouillon, couvrir et laisser cuire 1 heure.',
    'Une fois le potimarron cuit, mixer le tout et allonger selon le goût avec le reste du bouillon pour obtenir un velouté très onctueux.',
    'Décorer d\'un trait de crème, de quelques châtaignes caramélisées et de gouttes d\'huile de noix.',
  ]),
  // L'identifiant reconstitué contient un accent : on le reprend à l'identique,
  // sans quoi la fiche inventée resterait en double à côté de la vraie.
  r('docs-plats-pates-complètes-scampis', 'Pâtes complètes aux légumes et aux scampis', 'poisson', 35, 4, [
    [400, 'g', 'Pâtes complètes'], [200, 'g', 'Scampi'], [2, 'pc', 'Échalote'],
    [3, 'pc', 'Carotte'], [1, 'pc', 'Courgette'], [1, 'pc', 'Poivron'],
    [15, 'pc', 'Tomate cerise'], [10, 'cl', 'Lait'], [3, 'cc', 'Fromage frais'],
    [0.5, 'pc', 'Cube de bouillon de légumes'], [1, 'cc', 'Huile d\'olive'],
    [1, 'cc', 'Paprika'], [1, 'cc', 'Curcuma'], [1, 'cc', 'Curry'],
    [1, 'cc', 'Thym'], [1, 'cc', 'Origan'], [1, 'cc', 'Ail en poudre'],
    [1, 'pincée', 'Sel'], [1, 'pincée', 'Poivre'],
  ], [
    'Émincer les échalotes, couper les carottes et la courgette en petites rondelles, le poivron en lamelles et les tomates cerises en deux.',
    'Faire bouillir environ un demi-litre d\'eau et y ajouter le demi-cube de bouillon de légumes.',
    'Faire revenir les échalotes à la poêle avec une cuillère à café de matière grasse, puis ajouter les carottes. Quand elles commencent à coller, ajouter un peu de bouillon et répéter au fur et à mesure que l\'eau s\'évapore. Ajouter les poivrons.',
    'Pendant ce temps, faire cuire les pâtes comme indiqué sur l\'emballage.',
    'Dans une poêle à part, faire cuire les scampis et les assaisonner de sel, poivre et un peu d\'ail.',
    'Ajouter les courgettes aux autres légumes, les laisser cuire 3 à 4 minutes, puis ajouter un peu de lait et le fromage frais. Assaisonner ; si la sauce est trop liquide, ajouter un peu de Maïzena.',
    'Deux à trois minutes avant la fin de cuisson, ajouter les tomates cerises.',
    'Ajouter les scampis cuits à la sauce et mélanger la sauce aux pâtes.',
  ]),
  r('docs-plats-pates-brioches-choco', 'Petites brioches aux pépites de chocolat', 'dessert', 90, 5, [
    [175, 'g', 'Farine'], [4, 'g', 'Levure de boulanger'], [30, 'ml', 'Lait'],
    [50, 'g', 'Compote de pommes'], [25, 'g', 'Huile de coco'],
    [40, 'g', 'Pépites de chocolat'], [1, 'pc', 'Œuf'], [1, 'pincée', 'Sel'],
  ], [
    'Préchauffer le four à 180 °C.',
    'Faire légèrement chauffer le lait au micro-ondes quelques secondes pour qu\'il soit tiède, sans être chaud, puis y diluer la levure. Couvrir d\'un torchon et laisser reposer 10 minutes.',
    'Pendant ce temps, ajouter dans un saladier la farine, l\'œuf, la compote, la pincée de sel, et en dernier l\'huile de coco préalablement fondue. Mélanger le tout.',
    'Ajouter le mélange lait-levure et pétrir 5 à 10 minutes à la main, ou 5 minutes au robot à vitesse 1.',
    'Former une boule et laisser gonfler 45 minutes dans un four éteint, recouverte d\'un torchon.',
    'Dégazer la boule, ajouter les pépites de chocolat et mélanger pour les incorporer.',
    'Diviser la pâte en petites boules : deux pour de belles brioches, cinq ou six pour de plus petites.',
    'Laisser à nouveau reposer 45 minutes à couvert dans le four éteint pour une meilleure pousse.',
    'Enfourner 10 à 12 minutes à 180 °C. Ces brioches peuvent être congelées.',
  ]),
];
